### ISSUE TITLE
Playing audio stops after short time when debug console not active

### ISSUE THREAD

**Issue by cottonwool** [yoichiro/chromeos-filesystem-cifs#97] opened 2015-08-18 21:05 UTC
I have SMB/CIFS giving me access to a share on a Win 7 PC.
I am playing audio files using the built in audio player.

If I have the SMB/CIFS extension debug console window open there is no problem playing files of many minutes length (e.g. 20 minutes) one after the other.

If I don't open the debug console window then the audio playout hangs up after around 1.5 minutes to 2 minutes.

I can reproduce this problem easily as long as I don't have the console window active :-(

Watching the SMB transactions on the PC using Wireshark I see [RST, ACK] events with Win=0 Len=0 occurring twice in close succession and no more traffic after the second time.

**Comment by cottonwool** [comment] 2015-08-18 21:15
192.168.178.20  is the WIn 7 PC
192.168.178.22  is the Chromebook

![wireshark rst ack 20150818 2125](https://cloud.githubusercontent.com/assets/8496854/9342892/622b8d62-45f6-11e5-9331-9ea184d59cfe.png)

**Comment by cottonwool** [comment] 2015-08-18 21:32
Some time after this problem occurred (after typing the above report in) the SMB/CIFS extension on the Chromebook had five pop-ups:
Network error occured: -101
Unknown packet received
13108120: UNKNOWN
Unknown packet received
Unknown packet received

The first pop-up listed above appeared at the bottom of the stack on the screen, the last at the top. 
I had stopped the capture at the PC so I don't know if anything restarted.
Selecting another audio file and playing it gets things moving again for a short while (e.g 2'39") before another pair of [RST, ACK] events occur.

**Comment by yoichiro** [comment] 2015-09-03 11:55
@cottonwool Hmm... I'm not sure what is the reason. Well, I released a new version 2.0.0 today, and the version includes a SMB2 supporting. When you try to access to your Win7, my app should negotiate with the SMB2 protocol. Probably, my SMB2 implementation may solve this issue, I guess. Could you install the new version, and could you confirm whether this issue is reproduced or not with the new version?

**Comment by yoichiro** [comment] 2015-09-18 13:42
I close this issue, because I could not get more information to fix this issue from the reporter. Sorry.

**Closed as completed by yoichiro** 2015-09-18 13:42 UTC

**Comment by cottonwool** [comment] 2015-09-18 15:38
Version 2.11 seems to have fixed this issue.
Although this issue is already closed I want to confirm it is now fixed
In testing so far audio played for >20 mins with SMB1 and > 20 mins with SMB2.
This is as long as I have had time to test for and both times are >> than the previous time to failure.
