### ISSUE TITLE
Issue joining Samba share on Asus Router

### ISSUE THREAD

**Issue by LCalrissian** [yoichiro/chromeos-filesystem-cifs#112] opened 2015-09-09 04:21 UTC
I'm having trouble connecting to a Samba share on an ASUS router.  I am able to mount the share in Windows.  With this extension, I get no response at all from the extension, and it seems to freeze up the Samba service on the router - I can't access the router's admin page for Samba, and I need to reboot it in order to get there.   See the log below.  Please let me know if there is any other way I can help you troubleshoot.

connect
background.js:6372 Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
background.js:6372 NegotiateProtocolRequest {types_: Types, dialects: Array[0], dialects_: Array[2]}
background.js:6372 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 58, packetHelper_: PacketHelper}
background.js:6379 Negotiated with SMB1/CIFS
background.js:6379 CAP_EXTENDED_SECURITY: false
background.js:6379 CAP_COMPRESSED_DATA: false
background.js:6379 CAP_BULK_TRANSFER: false
background.js:6379 CAP_UNIX: true
background.js:6379 CAP_LARGE_WRITEX: true
background.js:6379 CAP_LARGE_READX: true
background.js:6379 CAP_INFOLEVEL_PASSTHROUGH: true
background.js:6379 CAP_DFS: false
background.js:6379 CAP_NT_FIND: true
background.js:6379 CAP_LOCK_AND_READ: true
background.js:6379 CAP_LEVEL_II_OPLOCKS: true
background.js:6379 CAP_STATUS32: true
background.js:6379 CAP_RPC_REMOTE_APIS: true
background.js:6379 CAP_NT_SMBS: true
background.js:6379 CAP_LARGE_FILES: true
background.js:6379 CAP_UNICODE: true
background.js:6379 CAP_MPX_MODE: false
background.js:6379 CAP_RAW_MODE: true
background.js:6379 NEGOTIATE_SECURITY_SIGNATURES_REQUIRED: 0
background.js:6379 NEGOTIATE_SECURITY_SIGNATURES_ENABLED: 0
background.js:6379 NEGOTIATE_SECURITY_CHALLENGE_RESPONSE: 1
background.js:6379 NEGOTIATE_SECURITY_USER_LEVEL: 1
background.js:6372 Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
background.js:6372 NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 3, maxMpxCount_: 50, maxNumberVCs_: 1…}
background.js:6372 Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 0, errorCode_: 0…}
background.js:6372 SessionSetupAndxRequest {types_: Types, maxBufferSize_: 16644, maxMpxCount_: 50, vcNumber_: 1, sessionKey_: 894…}
background.js:6372 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 182, packetHelper_: PacketHelper}
background.js:6372 Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 0, errorCode_: 0…}
background.js:6372 Header {types_: Types, protocol_: "SMB", command_: 117, errorClass_: 0, errorCode_: 0…}
background.js:6372 TreeConnectAndxRequest {types_: Types, path_: "\192.168.2.1\IPC$", service_: "?????"}
background.js:6372 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 88, packetHelper_: PacketHelper}
background.js:6372 Header {types_: Types, protocol_: "SMB", command_: 117, errorClass_: 0, errorCode_: 0…}
background.js:6372 TreeConnectAndxResponse {types_: Types, responseUtils_: ResponseUtils, supportSearchBits_: true, shareIsInDfs_: false, service_: "IPC"}
background.js:6372 Header {types_: Types, protocol_: "SMB", command_: 162, errorClass_: 0, errorCode_: 0…}
background.js:6372 NtCreateAndxRequest {types_: Types, flags_: 22, rootDirectoryFId: 0, desiredAccess_: 131487, allocationSize_: 0…}
background.js:6372 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 100, packetHelper_: PacketHelper}
background.js:6372 Header {types_: Types, protocol_: "SMB", command_: 162, errorClass_: 0, errorCode_: 0…}
background.js:6372 NtCreateAndxResponse {types_: Types, responseUtils_: ResponseUtils, opLockLevel_: 0, fid: null, createDisposition_: 1…}
background.js:6372 Header {types_: Types, protocol_: "SMB", command_: 37, errorClass_: 0, errorCode_: 0…}
background.js:6372 TransactionRequest {types_: Types, transactionName_: "\PIPE\", flags_: 0, timeout_: 0, parameter_: null…}
background.js:6372 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 154, packetHelper_: PacketHelper}
background.js:6372 Header {types_: Types, protocol_: "SMB", command_: 37, errorClass_: 0, errorCode_: 0…}
background.js:6372 DceRpcBindAck {types_: Types, dceRpc_: DceRpc, ackResult_: 0}
background.js:6372 Header {types_: Types, protocol_: "SMB", command_: 37, errorClass_: 0, errorCode_: 0…}
background.js:6372 TransactionRequest {types_: Types, transactionName_: "\PIPE\", flags_: 0, timeout_: 0, parameter_: null…}
background.js:6372 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 178, packetHelper_: PacketHelper}
background.js:6372 Header {types_: Types, protocol_: "SMB", command_: 37, errorClass_: 5, errorCode_: 32768…}
background.js:6372 Header {types_: Types, protocol_: "SMB", command_: 46, errorClass_: 0, errorCode_: 0…}
background.js:6372 ReadAndxRequest {types_: Types, requestUtils_: RequestUtils, fid_: 16930, offset_: 0, length_: 57344}
background.js:6372 Header {types_: Types, protocol_: "SMB", command_: 46, errorClass_: 0, errorCode_: 0…}
background.js:6372 ReadAndxResponse {types_: Types, responseUtils_: ResponseUtils, available_: 0, dataCompactionMode_: 0, dataLength_: 1472…}
background.js:6372 Header {types_: Types, protocol_: "SMB", command_: 46, errorClass_: 0, errorCode_: 0…}
background.js:6372 ReadAndxRequest {types_: Types, requestUtils_: RequestUtils, fid_: 16930, offset_: 1472, length_: 57344}
background.js:6372 Header {types_: Types, protocol_: "SMB", command_: 46, errorClass_: 0, errorCode_: 0…}
background.js:6372 ReadAndxResponse {types_: Types, responseUtils_: ResponseUtils, available_: 0, dataCompactionMode_: 0, dataLength_: 0…}available_: 0dataCompactionMode_: 0dataLength_: 0data_: Uint8Array[0]responseUtils_: ResponseUtilstypes_: Types__proto__: ReadAndxResponse
extensions::uncaught_exception_handler:8 Error in event handler for sockets.tcp.onReceive: TypeError: Cannot read property 'concatBuffers' of undefined
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:15231:58)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:15486:13)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:15497:17)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:15522:21)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:14219:21)
    at ChromeSocket2.fetch (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:14448:26)
    at ChromeSocket2.fetch (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:14450:26)
    at _appendReceivedData (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:14333:14)
    at ChromeSocket2.onReceive (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:14407:33)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:14392:22)

**Comment by yoichiro** [comment] 2015-09-18 13:28
@LCalrissian Probably, this issue has already been fixed by the latest version. Could you do a test to confirm whether this issue is reproduced or not with the latest version 2.1.1?

**Comment by yoichiro** [comment] 2015-10-12 11:31
@LCalrissian I close this issue, because you could not post the reply above. Thank you for the report!

**Closed as completed by yoichiro** 2015-10-12 11:31 UTC
