### ISSUE TITLE
Want to mount a directory in a mounted shared resource directly

### ISSUE THREAD

**Issue by smbuser** [yoichiro/chromeos-filesystem-cifs#118] opened 2015-09-15 08:20 UTC
Hi @yoichiro again

I created new issues because the previous #78 was closed.
In my company we don't use FreeNAS, Linux Servers - we use only Windows Servers enterprise.  We have folder "home" which is a share and from laptops with windows 7, windows xp we have access to folders below folder home. 

![share_home_opis](https://cloud.githubusercontent.com/assets/13346531/9870818/86a1ff2e-5b8f-11e5-9868-09ba30390ef3.png)

When I use chromebook and your applications -  Shared resource name is fkonwinm, in log file I have
![sciezka](https://cloud.githubusercontent.com/assets/13346531/9871149/d8f4c99e-5b91-11e5-9180-e4b37a0b2e51.PNG)

In path_: \\cl-dc0001\fkonwinm missing folder home.
the correct path to folder fkonwinm in windows -  \\cl-dc0001\home\fkonwinm

Thanks for your reply

Smbuser

**Comment by yoichiro** [comment] 2015-09-18 13:30
@smbuser Could you post the debug log by the following steps?
https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by smbuser** [comment] 2015-09-21 06:20
Object {serverName: "cl-dc0001", serverPort: "445", username: "fkonwinm", password: "", domainName: "DLKPL"…}
background.js:6381 Client#login
background.js:6388 connect
background.js:6388 Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
background.js:6388 NegotiateProtocolRequest {types_: Types, dialects: Array[0], dialects_: Array[2]}
background.js:6388 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 58, packetHelper_: PacketHelper}
background.js:6381 writePacket
background.js:6388 FF53 4D42 7200 0000 0018 03C8 0000 0000  .SMBr...........
0000 0000 0000 0000 0000 0700 0000 0100  ................
0017 0002 4E54 204C 4D20 302E 3132 0002  ....NT LM 0.12..
534D 4220 322E 3030 3200  SMB 2.002.

background.js:6381 readPacket
background.js:6381 _readPacketSize
background.js:6381 _readPacketSize - 2
background.js:6381 readPacket: 192
background.js:6388 FF53 4D42 7200 0000 0098 03C8 0000 0000  .SMBr...........
0000 0000 0000 0000 0000 0700 0000 0100  ................
1100 0003 3200 0100 0441 0000 0000 0100  ....2....A......
0000 0000 FDF3 0180 7432 4ADF 34F4 D001  ........t2J.4...
88FF 007B 00FF A450 0E39 D987 4D90 17E3  ...{...P.9..M...
0113 E93D 5760 6906 062B 0601 0505 02A0  ...=W`i..+......
5F30 5DA0 3030 2E06 092A 8648 82F7 1201  _0].00...*.H....
0202 0609 2A86 4886 F712 0102 0206 0A2A  ....*.H........*
8648 86F7 1201 0202 0306 0A2B 0601 0401  .H.........+....
8237 0202 0AA3 2930 27A0 251B 2363 6C2D  .7....)0'.%.#cl-
6463 3030 3031 2440 444C 4B50 4C2E 504C  dc0001$@DLKPL.PL
2E44 414C 4B49 412E 4752 4F55 502E 5645  .DALKIA.GROUP.VE

background.js:6395 Negotiated with SMB1/CIFS
background.js:6395 CAP_EXTENDED_SECURITY: true
background.js:6395 CAP_COMPRESSED_DATA: false
background.js:6395 CAP_BULK_TRANSFER: false
background.js:6395 CAP_UNIX: false
background.js:6395 CAP_LARGE_WRITEX: true
background.js:6395 CAP_LARGE_READX: true
background.js:6395 CAP_INFOLEVEL_PASSTHROUGH: true
background.js:6395 CAP_DFS: true
background.js:6395 CAP_NT_FIND: true
background.js:6395 CAP_LOCK_AND_READ: true
background.js:6395 CAP_LEVEL_II_OPLOCKS: true
background.js:6395 CAP_STATUS32: true
background.js:6395 CAP_RPC_REMOTE_APIS: true
background.js:6395 CAP_NT_SMBS: true
background.js:6395 CAP_LARGE_FILES: true
background.js:6395 CAP_UNICODE: true
background.js:6395 CAP_MPX_MODE: false
background.js:6395 CAP_RAW_MODE: true
background.js:6395 NEGOTIATE_SECURITY_SIGNATURES_REQUIRED: 0
background.js:6395 NEGOTIATE_SECURITY_SIGNATURES_ENABLED: 0
background.js:6395 NEGOTIATE_SECURITY_CHALLENGE_RESPONSE: 1
background.js:6395 NEGOTIATE_SECURITY_USER_LEVEL: 1
background.js:6388 Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
background.js:6388 NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 3, maxMpxCount_: 50, maxNumberVCs_: 1…}
background.js:6388 Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 0, errorCode_: 0…}
background.js:6388 SessionSetupAndxRequest {types_: Types, maxBufferSize_: 16644, maxMpxCount_: 50, vcNumber_: 1, sessionKey_: 0…}
background.js:6388 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160, packetHelper_: PacketHelper}
background.js:6381 writePacket
background.js:6388 FF53 4D42 7300 0000 0018 03C8 0000 0000  .SMBs...........
0000 0000 0000 0000 0000 0700 0000 0200  ................
0CFF 0000 0004 4132 0001 0000 0000 0029  ......A2.......)
0000 0000 0054 0000 8065 004E 544C 4D53  .....T...e.NTLMS
5350 0001 0000 0005 3208 2001 0001 0020  SP......2. .... 
0000 0008 0008 0021 0000 003F 4653 505F  .......!...?FSP_
4349 4653 4300 6800 7200 6F00 6D00 6500  CIFSC.h.r.o.m.e.
4F00 5300 0000 4600 6900 6C00 6500 2000  O.S...F.i.l.e. .
5300 7900 7300 7400 6500 6D00 2000 6600  S.y.s.t.e.m. .f.
6F00 7200 2000 4300 4900 4600 5300 0000  o.r. .C.I.F.S...

background.js:6381 readPacket
background.js:6381 _readPacketSize
background.js:6381 _readPacketSize - 2
background.js:6381 readPacket: 453
background.js:6388 FF53 4D42 7316 0000 C098 03C8 0000 0000  .SMBs...........
0000 0000 0000 0000 0000 0700 0308 0200  ................
04FF 00C5 0100 000E 019A 014E 544C 4D53  ...........NTLMS
5350 0002 0000 000A 000A 0038 0000 0005  SP.........8....
0289 225E 0284 A430 A72A 0100 0000 0000  .."^...0.*......
0000 00CC 00CC 0042 0000 0005 02CE 0E00  .......B........
0000 0F44 004C 004B 0050 004C 0002 000A  ...D.L.K.P.L....
0044 004C 004B 0050 004C 0001 0012 0043  .D.L.K.P.L.....C
004C 002D 0044 0043 0030 0030 0030 0031  .L.-.D.C.0.0.0.1
0004 0030 0064 006C 006B 0070 006C 002E  ...0.d.l.k.p.l..
0070 006C 002E 0064 0061 006C 006B 0069  .p.l...d.a.l.k.i
0061 002E 0067 0072 006F 0075 0070 002E  .a...g.r.o.u.p..
0076 0065 0003 0044 0063 006C 002D 0064  .v.e...D.c.l.-.d
0063 0030 0030 0030 0031 002E 0064 006C  .c.0.0.0.1...d.l
006B 0070 006C 002E 0070 006C 002E 0064  .k.p.l...p.l...d
0061 006C 006B 0069 0061 002E 0067 0072  .a.l.k.i.a...g.r
006F 0075 0070 002E 0076 0065 0005 0024  .o.u.p...v.e...$
0070 006C 002E 0064 0061 006C 006B 0069  .p.l...d.a.l.k.i
0061 002E 0067 0072 006F 0075 0070 002E  .a...g.r.o.u.p..
0076 0065 0000 0000 0084 5700 6900 6E00  .v.e......W.i.n.
6400 6F00 7700 7300 2000 5300 6500 7200  d.o.w.s. .S.e.r.
7600 6500 7200 2000 3200 3000 3000 3300  v.e.r. .2.0.0.3.
2000 5200 3200 2000 3300 3700 3900 3000   .R.2. .3.7.9.0.
2000 5300 6500 7200 7600 6900 6300 6500   .S.e.r.v.i.c.e.
2000 5000 6100 6300 6B00 2000 3200 0000   .P.a.c.k. .2...
5700 6900 6E00 6400 6F00 7700 7300 2000  W.i.n.d.o.w.s. .
5300 6500 7200 7600 6500 7200 2000 3200  S.e.r.v.e.r. .2.
3000 3000 3300 2000 5200 3200 2000 3500  0.0.3. .R.2. .5.
2E00 3200 00 ..2..

background.js:6388 Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 22, errorCode_: 49152…}
background.js:6395 NTLMSSP_NEGOTIATE_UNICODE: true
background.js:6395 NTLMSSP_NEGOTIATE_OEM: false
background.js:6395 NTLMSSP_REQUEST_TARGET: true
background.js:6395 NTLMSSP_NEGOTIATE_SIGN: false
background.js:6395 NTLMSSP_NEGOTIATE_SEAL: false
background.js:6395 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
background.js:6395 NTLMSSP_NEGOTIATE_LM_KEY: false
background.js:6395 NTLMSSP_NEGOTIATE_NETWARE: false
background.js:6395 NTLMSSP_NEGOTIATE_NTLM: true
background.js:6395 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
background.js:6395 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
background.js:6395 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
background.js:6395 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
background.js:6395 NTLMSSP_TARGET_TYPE_DOMAIN: true
background.js:6395 NTLMSSP_TARGET_TYPE_SERVER: false
background.js:6395 NTLMSSP_TARGET_TYPE_SHARE: false
background.js:6395 NTLMSSP_NEGOTIATE_NTLM2: true
background.js:6395 NTLMSSP_REQUEST_INIT_RESPONSE: false
background.js:6395 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
background.js:6395 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
background.js:6395 NTLMSSP_NEGOTIATE_TARGET_INFO: true
background.js:6395 NTLMSSP_NEGOTIATE_128: true
background.js:6395 NTLMSSP_NEGOTIATE_KEY_EXCH: false
background.js:6395 NTLMSSP_NEGOTIATE_56: false
background.js:6388 Header {types_: Types, protocol_: "SMB", command_: 115, errorClass_: 0, errorCode_: 0…}
background.js:6388 SessionSetupAndxRequest {types_: Types, maxBufferSize_: 16644, maxMpxCount_: 50, vcNumber_: 1, sessionKey_: 0…}
background.js:6388 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 502, packetHelper_: PacketHelper}
background.js:6381 writePacket
background.js:6388 FF53 4D42 7300 0000 0018 03C8 0000 0000  .SMBs...........
0000 0000 0000 0000 0000 0700 0308 0300  ................
0CFF 0000 0004 4132 0001 0000 0000 007E  ......A2.......~
0100 0000 0054 0000 80BB 014E 544C 4D53  .....T.....NTLMS
5350 0003 0000 0018 0018 0040 0000 00FC  SP.........@....
00FC 0058 0000 000A 000A 0054 0100 0010  ...X.......T....
0010 005E 0100 0010 0010 006E 0100 0000  ...^.......n....
0000 0000 0000 0001 0008 00EA 6CB5 7432  ............l.t2
CE1A 5FF0 8B72 1BBD DD94 1DFF 73F0 FF5C  .._..r......s..\
947F 3909 FA67 A96F E9A7 9609 8671 A9AC  ..9..g.o.....q..
D57F 0601 0100 0000 0000 0030 7B7A DE34  ...........0{z.4
F4D0 019F D45B 5AC4 0700 0000 0000 0002  .....[Z.........
000A 0044 004C 004B 0050 004C 0001 0012  ...D.L.K.P.L....
0043 004C 002D 0044 0043 0030 0030 0030  .C.L.-.D.C.0.0.0
0031 0004 0030 0064 006C 006B 0070 006C  .1...0.d.l.k.p.l
002E 0070 006C 002E 0064 0061 006C 006B  ...p.l...d.a.l.k
0069 0061 002E 0067 0072 006F 0075 0070  .i.a...g.r.o.u.p
002E 0076 0065 0003 0044 0063 006C 002D  ...v.e...D.c.l.-
0064 0063 0030 0030 0030 0031 002E 0064  .d.c.0.0.0.1...d
006C 006B 0070 006C 002E 0070 006C 002E  .l.k.p.l...p.l..
0064 0061 006C 006B 0069 0061 002E 0067  .d.a.l.k.i.a...g
0072 006F 0075 0070 002E 0076 0065 0005  .r.o.u.p...v.e..
0024 0070 006C 002E 0064 0061 006C 006B  .$.p.l...d.a.l.k
0069 0061 002E 0067 0072 006F 0075 0070  .i.a...g.r.o.u.p
002E 0076 0065 0000 0000 0000 0000 0044  ...v.e.........D
004C 004B 0050 004C 0066 006B 006F 006E  .L.K.P.L.f.k.o.n
0077 0069 006E 006D 0046 0053 0050 005F  .w.i.n.m.F.S.P._
0043 0049 0046 0053 0000 4300 6800 7200  .C.I.F.S..C.h.r.
6F00 6D00 6500 4F00 5300 0000 4600 6900  o.m.e.O.S...F.i.
6C00 6500 2000 5300 7900 7300 7400 6500  l.e. .S.y.s.t.e.
6D00 2000 6600 6F00 7200 2000 4300 4900  m. .f.o.r. .C.I.
4600 5300 0000  F.S...

background.js:6381 readPacket
background.js:6381 _readPacketSize
background.js:6381 _readPacketSize - 2
background.js:6381 readPacket: 183
background.js:6388 FF53 4D42 7300 0000 0098 03C8 0000 0000  .SMBs...........
0000 0000 0000 0000 0000 0700 0308 0300  ................
04FF 00B7 0000 0000 008C 0000 5700 6900  ............W.i.
6E00 6400 6F00 7700 7300 2000 5300 6500  n.d.o.w.s. .S.e.
7200 7600 6500 7200 2000 3200 3000 3000  r.v.e.r. .2.0.0.
3300 2000 5200 3200 2000 3300 3700 3900  3. .R.2. .3.7.9.
3000 2000 5300 6500 7200 7600 6900 6300  0. .S.e.r.v.i.c.
6500 2000 5000 6100 6300 6B00 2000 3200  e. .P.a.c.k. .2.
0000 5700 6900 6E00 6400 6F00 7700 7300  ..W.i.n.d.o.w.s.
2000 5300 6500 7200 7600 6500 7200 2000   .S.e.r.v.e.r. .
3200 3000 3000 3300 2000 5200 3200 2000  2.0.0.3. .R.2. .
3500 2E00 3200 00 5...2..

background.js:6381 Client#connectSharedResource
background.js:6388 Header {types_: Types, protocol_: "SMB", command_: 117, errorClass_: 0, errorCode_: 0…}
background.js:6388 TreeConnectAndxRequest {types_: Types, path_: "\\cl-dc0001\FKONWINM", service_: "?????"}
background.js:6388 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 92, packetHelper_: PacketHelper}
background.js:6381 writePacket
background.js:6388 FF53 4D42 7500 0000 0018 03C8 0000 0000  .SMBu...........
0000 0000 0000 0000 0000 0700 0308 0400  ................
04FF 0000 0000 0001 0031 0000 5C00 5C00  .........1..\.\.
6300 6C00 2D00 6400 6300 3000 3000 3000  c.l.-.d.c.0.0.0.
3100 5C00 4600 4B00 4F00 4E00 5700 4900  1.\.F.K.O.N.W.I.
4E00 4D00 0000 3F3F 3F3F 3F00  N.M...?????.

background.js:6381 readPacket
background.js:6381 _readPacketSize
background.js:6381 _readPacketSize - 2
background.js:6381 readPacket: 35
background.js:6388 FF53 4D42 75CC 0000 C098 03C8 0000 0000  .SMBu...........
0000 0000 0000 0000 0000 0700 0308 0400  ................
0000 00 ...

**Comment by yoichiro** [comment] 2015-10-12 22:16
@smbuser You should enter "home" string as the shared directory.

**Comment by smbuser** [comment] 2015-10-13 14:39
Hi @yoichiro 

When I enter "home" string as the shared directory I have access to all folders in the directory home, 
![screenshot_1](https://cloud.githubusercontent.com/assets/13346531/10457573/54ae42ea-71c7-11e5-9472-e29b0d09b515.png)

but I want to have access only to my folder fkonwinm in your application,because I want to mount only one folder, so when I enter fkonwinm as shared resource name - I have error "BAD_NETWORK_NAME ". 
In Windows 7 I can mount my folder fkonwinm and any others, below folder home - \cl-dc0001\home\fkonwinm   - In this case I don't have any errors. How can I fix it?

Thanks for your replay
smbuser

**Comment by yoichiro** [comment] 2015-10-13 14:56
@smbuser I think that the "fkonwinm" is NOT a shared resource, but it is a folder... Well, could you capture packets between your Windows 7 and the target file server by the following steps?
https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-capture-packets-with-Wireshark
I want to know the correct communication you're expecting from the captured packets log.

**Comment by smbuser** [comment] 2015-10-14 05:35
@yoichiro 
"fkonwinm" is NOT a shared resource - this is a folder

**Comment by yoichiro** [comment] 2015-10-24 01:20
@smbuser Ping.

**Comment by yoichiro** [comment] 2015-10-26 00:27
@smbuser Sorry, I could understand your opinion. My understanding is:
- You want to mount "\cl-dc0001\home\fkonwinm" only.
- However, my app cannot mount the \home\fkonwinm directory only.
- Therefore, my app lists many folders including the fkonwinm directory, and you must find and double-click the folder. Of course, you don't want to do that.

When you enter the "fkonwinm" as a shared resource name, of course, the error code "c0000000cc" occurs. This is correct specification, because the "fkonwinm" is NOT a shared resource.

At least, Windows also cannot mount the subdirectory directly, I think (in this case, the "mount" means assigning a shared resource to some drive letter).

Hmm... will you be able to be happy if you can decide a root directory by yourself in the mounted shared resource?

**Comment by yoichiro** [comment] 2015-10-26 00:28
I changed the issue title, because this is NOT a bug but requirement.

**Comment by smbuser** [comment] 2015-10-26 06:30
Hi @yoichiro 

Thanks for your replay

"You want to mount "\cl-dc0001\home\fkonwinm" only. - **exactly I want to mount only one folder**"

Windows can mount subdirectory to some drive letter

...Hmm... will you be able to be happy if you can decide a root directory by yourself in the mounted shared resource? **Can I try this solution?**

**Comment by yoichiro** [comment] 2015-10-26 11:36
@smbuser "will you be able to be happy if you can decide a root directory by yourself in the mounted shared resource? Can I try this solution?" Of course, You cannot do that now. I intend to add a new feature to do that.

**Comment by yoichiro** [comment] 2015-10-27 11:45
https://github.com/yoichiro/chromeos-filesystem-cifs/pull/143

**Comment by yoichiro** [comment] 2015-10-27 12:05
@smbuser I have released a new version 2.6.0 including a new feature to specify a root directory you want to mount. Could you confirm whether or not the new feature is required by you?

**Comment by smbuser** [comment] 2015-10-27 13:57
Hi @yoichiro 

This new feature is excellent. Can I mount my home folder fkonwinm ald other folders

Thanks for your help

**Comment by yoichiro** [comment] 2015-10-27 15:04
@smbuser You need to enter two values like the following: Shared Resource Name = home, Root Directory = fkonwinm.

**Comment by smbuser** [comment] 2015-10-30 07:15
Hi @yoichiro 

You need to enter two values like the following: Shared Resource Name = home, Root Directory = fkonwinm. - **this works perfect** 

I have a question about name mounted shared folders. Can you change name 
![screenshot 2015-10-30 at 07 53 52](https://cloud.githubusercontent.com/assets/13346531/10840068/78acd064-7edb-11e5-9b3b-6a634a472121.png)![screenshot 2015-10-30 at 07 58 18](https://cloud.githubusercontent.com/assets/13346531/10840135/2c173a04-7edc-11e5-9599-ad86d5e212d3.png)
on name of server(name of root directory) ?

Thanks for your help.
smbuser

**Comment by yoichiro** [comment] 2015-11-01 09:49
@smbuser I intend to create a new feature which users can name for each connection setting #138. I close this issue. Thank you for this reporting.

**Closed as completed by yoichiro** 2015-11-01 09:49 UTC
Labels: enhancement
