### ISSUE TITLE
No operation on a Netgear R7000 router?

### ISSUE THREAD

**Issue by des421** [yoichiro/chromeos-filesystem-cifs#81] opened 2015-07-30 18:46 UTC
I assume the subject is the problem? Since there is evidence the app works. But not for me on either my Pixel LS or an Asus C200, both connected WirelssAC. No share name will be resolved period, The "rope"/search returns nothing, etc. I have AndSMB on an Android phone for which my 4 Windows computers and their shares plus the Netgear Readyshare NAS (a HDD in a USB enclosure connected USB 3.0) are available everything to everybody, so I must understand something about how this works?Definition of Host Name, Share Name, Computer Name, Log-on Credentials,etc. I thought until now!

DES

**Comment by yoichiro** [comment] 2015-08-09 04:51
@des421 Could you check a debug log output on the console tab of the DevTools by using the steps? https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by des421** [comment] 2015-08-09 14:02
```
The example shown is for the
      "File System for Dropbox".

      My problem is with the SMB/CIFS/Windows(R) extension, which
      includes no such "background page" link?

      Once just now SMB did Find the "R7000" and display it's IP
      address, but would not accept the Router's Logon info used to
      access it's setup. I'm trying to access the Readyshare NAS, a
      USB 3.0 connected HDD, that has no Logon credentials, is just
      seen as an open network share. In repeated tries SMB has only
      even found the R7000 once, with 4 other Windows computers with
      shares on the network that have never been discovered?

      DES


On 8/8/2015 11:51 PM, Yoichiro Tanaka
  wrote:


  @des421 Could you check a debug log
    output on the console tab of the DevTools by using the steps? https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by yoichiro** [comment] 2015-08-09 21:15
@des421 The way to check the debug log is the same as the Dropbox app. I cannot understand your issue, therefore, you should provide the log to me.

**Comment by des421** [comment] 2015-08-10 00:15
I'm learning... you've left out a "small" step. To be able to supply the
log you want requires the Chromebook to be in Developer's Mode. To put the
Chromebook in Developer's Mode requires resetting it, clearing all user
data, and is apparently unsupported by Google. Thanks, but no thanks. I'll
wait for something that works.

DES

**Comment by yoichiro** [comment] 2015-08-10 01:20
I cannot fix your issue without a detail information. Close this issue. If you can get some information (ex. DevTools Console log), please a new issue with them.

**Closed as completed by yoichiro** 2015-08-10 01:20 UTC

**Comment by dkewley** [comment] 2015-08-13 22:27
@des421: Like you, my Chromebook is NOT in Developers Mode, and I'd strongly prefer to avoid Developers Mode.

That said, I can capture the DevTools console output just fine, following the instructions from @yoichiro. I'm curious why it's not working for you. From my experience, following those instructions does NOT require the Chromebook to be in Developers Mode.

When I browse chrome://extensions, and find the SMB/CIFS extension, it shows it's at version 1.5.0 and there is a "background page" link, as shown in the screenshot in the instructions from @yoichiro.

Is the extension version 1.5.0 for you? Is there definitely no "background page" link? Can you share a screenshot of that portion of the Extensions settings page so we can see what you're seeing?

**Comment by des421** [comment] 2015-08-14 00:35
I have 2 Chromebooks, An Asus C200 and a Pixel LS*, *which both behave
exactly the same. If a check block "Developer mode" at the top of the
Extensions page is checked then a "background page (inactive)" link is
shown for SMB/CIFS (and other extensions). Which when clicked shows a new
window including the "Console" tab which is totally empty, as would be
expected with the "inactive" indication. I suggest your Chromebook is
actually in Developer's Mode?

DES

**Comment by dkewley** [comment] 2015-08-14 01:53
@des421 : Ah, it appears there are two different senses of "Developer Mode". There's Developer Mode for the Chromebook as a whole, which as you wrote earlier, wipes your data, is unsupported, etc. Like you, I want to avoid this.

Then there's the "Developer Mode" checkbox on the Extensions page, which is named the same but is entirely different, it appears to me.

I have the DM checkbox on the Extension page checked, just as you suggested I did. I've had it checked so long, I forgot it existed. :) Perhaps @yoichiro should add an item to his instructions pointing out that this needs to be checked if it isn't already. I hadn't realized it must be checked in order to follow his debug log instructions.

But checking that box did not wipe my data, and does not give me the scary boot time warning that full Chrome OS DM would give according to my reading. It seems perfectly safe for you to use, dunno if you agree.

**Comment by des421** [comment] 2015-08-14 13:32
```
I was suggesting your
      Chromebook was "actually" in Developer's Mode. Not that the
      Developer Mode check box on the Extensions page was checked
      (which it would have to be to get the background page link
      displayed). Two different things. As I said, the background
      page link indicated "inactive" for me because I am not actually
      in DM, only the check box was checked. The results of opening
      the background page link when inactive are zero, blank, no
      logs, etc. 

On 8/13/2015 8:53 PM, David Kewley
  wrote:


  @des421 : Ah, it appears there are
    two different senses of "Developer Mode". There's Developer Mode
    for the Chromebook as a whole, which as you wrote earlier, wipes
    your data, is unsupported, etc. Like you, I want to avoid this.
  Then there's the "Developer Mode" checkbox on the Extensions
    page, which is named the same but is entirely different, it
    appears to me.
  I have the DM checkbox on the Extension page checked, just as
    you suggested I did. I've had it checked so long, I forgot it
    existed. :) Perhaps @yoichiro
    should add an item to his instructions pointing out that this
    needs to be checked if it isn't already. I hadn't realized it
    must be checked in order to follow his debug log instructions.
  But checking that box did not wipe my data, and does not give
    me the scary boot time warning that full Chrome OS DM would give
    according to my reading. It seems perfectly safe for you to use,
    dunno if you agree.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by dkewley** [comment] 2015-08-14 19:59
My Chromebook is NOT in full Developer Mode. Here's why I'm confident that's the case: a) I never put it in Developer Mode (it requires very specific, non-obvious, warning-laden steps that I have never executed), and b) from my reading about Developer Mode, I'd see a boot-time warning if my Chromebook was in Developer Mode, but I don't see any such warning. So being in DM is NOT the reason why it works for me but not for you. Something else is going on.

I agree that checking the "Developer Mode" checkbox on the Extensions page is necessary to see the "background page" link. I hadn't realized that before -- thanks for pointing that out.

I agree that the link will say "background page (inactive)" instead of "background page" if you have no active mount at that time. And I agree that if you click on "background page (inactive)", then go to the Console tab, there will be no logs there, since it's inactive.

But, you can click on "background page (inactive)", open up the (presently empty) Console tab, then make an SMB/CIFS mount attempt -- after you click the "MOUNT" button in the SMB/CIFS extension's dialog box, you should see logs appear in the Console. This is what I see happen.

If you do all that and still don't see the logs, then I'm curious why it works for me but not for you.

**Comment by des421** [comment] 2015-08-14 21:09
```
And you're correct, "stuff"
      appears (if you get things in the right order)! Both on the
      background page link and a new windows.html (whatever that is)
      link. I'm starting to feel stupid (but that's never been a
      long trip). OK, on the console tab is only a couple lines that
      pretty much agree with the unable to mount message but there's
      all kinds of whatever on the other tabs. How does one Save all
      this, or what's wanted, for submission? He closed my issue and
      I've deleted the directions in frustration. We have a
      translation problem here that reminds me of talking with some
      Penguins about Ubuntu back at v6.0.

      I freely admit to not knowing what's going on here. The app
      has only ever once recognized an entity "R7000" which
      apparently was the HTML router logon for configuration.
      Otherwise it can't serch out anything on this network. The
      router has a USB 3.0 connected HDD by the name of Readyshare,
      which is open, no credentials, and shows up on all the Windows
      computers network discovery (XP, W7, & W8.1). Each of 4
      computers has at least one network share which all of the
      other 3 can see without any problem. And SMB/CIFS can't find
      anything on the LAN period? I even have an Android app on my
      phone, AndSMB, that sees all of this without problem? I keep
      hoping it's just something dumb I'm missing? Does it actually
      work for you?

      DES

On 8/14/2015 2:59 PM, David Kewley
  wrote:


  My Chromebook is NOT in full Developer Mode. Here's why I'm
    confident that's the case: a) I never put it in Developer Mode
    (it requires very specific, non-obvious, warning-laden steps
    that I have never executed), and b) from my reading about
    Developer Mode, I'd see a boot-time warning if my Chromebook was
    in Developer Mode, but I don't see any such warning. So being in
    DM is NOT the reason why it works for me but not for you.
    Something else is going on.
  I agree that checking the "Developer Mode" checkbox on the
    Extensions page is necessary to see the "background page" link.
    I hadn't realized that before -- thanks for pointing that out.
  I agree that the link will say "background page (inactive)"
    instead of "background page" if you have no active mount at that
    time. And I agree that if you click on "background page
    (inactive)", then go to the Console tab, there will be no logs
    there, since it's inactive.
  But, you can click on "background page (inactive)", open up the
    (presently empty) Console tab, then make an SMB/CIFS mount
    attempt -- after you click the "MOUNT" button in the SMB/CIFS
    extension's dialog box, you should see logs appear in the
    Console. This is what I see happen.
  If you do all that and still don't see the logs, then I'm
    curious why it works for me but not for you.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by dkewley** [comment] 2015-08-15 06:58
@des421 : Sorry the following is so long. I tried to keep it as short and organized as I could.

Stepping back from how to get the troubleshooting logs (more on that further below), let's take a look at your original issue.

If I understand correctly, I think that your main original issue is that magnifying glass in this app (Search for SMB servers on the local network) doesn't work for you. Is that right?

Indeed, I found today that the Search / magnifying glass wasn't working for me -- my NAS did not show up in the search results. Then I rebooted my Chromebook, and now Search shows my NAS.

For this failure of the magnifying glass, followed by success after reboot, I suspect the root cause is in Chrome, not the SMB/CIFS app. I think it'll be fixed in Chrome 45, coming out soon. I don't think there's anything @yoichiro can do until Chrome 45 is released in the Stable channel. See the indented gray text at the bottom for some technical details.

I suggest you try the following: Reboot your Chromebook, then very soon after reboot, try the Search (magnifying glass), and see if your servers show up now. 

If that fails, try to find the IP address for one (or more) of your servers using some other method, enter it manually in the "Server Host Name / IP Address" field, and make sure you fill in a valid User Name and Password for that server. Filling in these three fields (plus the already filled in Server Port Number field = 445) works for me against my NAS.

If you already tried this before, try it again at least once, just to see if it works this time. If it still doesn't work, then maybe something else is going on, and it may be worthwhile to capture debug logs like we've been discussing.

Could you let us know whether the Search functionality works after rebooting your Chromebook, and whether manually entering the IP address (and username and password) for one of your servers works?

If you'd like to capture logs for further troubleshooting, here are some suggestions.

Take a new look at @yoichiro's instructions, particularly step 3:

https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

Also, when he closed this bug, he said that if you can get further diagnostic info (e.g. a text copy or screenshot of the Console screen, as in Step 3 of the above link), you can open a new issue and provide that new diagnostic data, e.g. paste the text or attach the screenshot in your issue-opening comment. I suspect he won't be following this closed issue.

> More technical description follows:
> 
> I suspect that the underlying root cause of the magnifying glass failure that I'm seeing is fixed in this Chrome patch for the `chrome.mdns`` API:
> 
> https://chromium.googlesource.com/chromium/src/+/261ed0511eea1e3d10c5daa4dce563d1dfc7b5fc
> 
> See also this bug report, which this patch says it addresses -- it seems to describe behavior similar to what I'm seeing:
> https://code.google.com/p/chromium/issues/detail?id=504477
> 
> From what I can see, this patch is applied in Chrome version 45 (and 46), but not version 44. So once v45 goes Stable, I suspect the SMB/CIFS app's magnifying glass may work more reliably.
> 
> I'm not sure, but it might help if if @yoichiro adds functionality for the new `forceDiscovery` method documented here: https://developer.chrome.com/apps/mdns, which appears in v45.
> 
> In order to see the `chrome.mdns` API in use in this SMB/CIFS app, I needed to first disable then re-enable this app in the chrome://extensions page, then click on the background page link, then open the console tab. Now there are one or more log entries regarding `chrome.mdns` at the top of the console.
> 
> Now when I do this, I see that `chrome.mdns` is reporting my NAS to the app (and indeed it shows up when I click the magnifying glass):
> 
> ![screenshot 2015-08-14 at 22 25 03](https://cloud.githubusercontent.com/assets/2658755/9287767/be7b508e-42db-11e5-896c-bd26037737d5.png)
> 
> Before the reboot, I was only seeing the "Array[0]" line, not the "Array[1]" line, which indicates that `chrome.mdns` was not reporting to the app that my NAS was announcing itself using mDNS. In fact the NAS has been reporting its presence the whole time using mDNS, it's just that `chrome.mdns` wasn't telling the SMB/CIFS app about it. Again, I suspect this is fixed in Chrome 45.

**Comment by des421** [comment] 2015-08-15 16:06
```
After re-booting the
      Chromebook the SMB/CIFS Search then finds only the "R7000",
      not the attached NAS or any of the Windows computers shares
      online at the time. The router setup is below. The router is
      at 192.168.1.1 with a Username of "admin" and a known
      non-default password, but none of that applies to the
      connected shares. Trying to connect to it via it's IP &
      credentials gets closer in that at least "something" happens,
      but results in an "NT- Access-Denied" error. Any of the below
      share associated names just can't be resolved. Not too
      surprisingly as neither are they discoverable. Windows XP has
      a direct connection to "\\Readyshare\T_Drive" as it was setup
      that way initially, it allows manual pointing to network
      shares. Windows 7 & 8.1 just discover "Readyshare"
      themselves with "T_Drive" as a subfolder. I appreciate your
      continued support, and will probably further diddle with this
      later. But am not too enthused with having to work at it. The
      whole idea behind the Chromebooks is "not" to have play
      Windows with them. All this is supposedly a work in progress
      inside Chrome OS anyway. As a result of this I have discovered
      how to Copy & Paste (in both Chrome OS and Android) now,
      and more. I'll get there. Thanks.





         







              Network/Device Name :







              Workgroup :















              Enable
              Access Method
              Link
              Port



              Network
                Connection
              \\readyshare
              -



              HTTP
              http://readyshare.routerlogin.net/shares
              80



              HTTPS
                (via internet)
              https://70.187.54.143/shares




              FTP
              ftp://readyshare.routerlogin.net/shares
              21



              FTP (via
                internet)
              ftp://70.187.54.143/shares
















         



      Available
            Network Folders














               
              Share
                  Name
              Read
                  Access
              Write
                  Access
              Folder
                  Name
              Volume
                  Name
              Total
                  Space
              Free
                  Space



              \\readyshare\T_Drive
              All
                - no password
              All
                - no password
              T:\
              NAS
              298.1G
              193.6G


















              Edit        





On 8/15/2015 1:58 AM, David Kewley
  wrote:


  @des421 : Sorry the following is so
    long. I tried to keep it as short and organized as I could.
  Stepping back from how to get the troubleshooting logs (more on
    that further below), let's take a look at your original issue.
  If I understand correctly, I think that your main original
    issue is that magnifying glass in this app (Search for SMB
    servers on the local network) doesn't work for you. Is that
    right?
  Indeed, I found today that the Search / magnifying glass wasn't
    working for me -- my NAS did not show up in the search results.
    Then I rebooted my Chromebook, and now Search shows my NAS.
  For this failure of the magnifying glass, followed by success
    after reboot, I suspect the root cause is in Chrome, not the
    SMB/CIFS app. I think it'll be fixed in Chrome 45, coming out
    soon. I don't think there's anything @yoichiro
    can do until Chrome 45 is released in the Stable channel. See
    the indented gray text at the bottom for some technical details.
  I suggest you try the following: Reboot your Chromebook, then
    very soon after reboot, try the Search (magnifying glass), and
    see if your servers show up now. 
  If that fails, try to find the IP address for one (or more) of
    your servers using some other method, enter it manually in the
    "Server Host Name / IP Address" field, and make sure you fill in
    a valid User Name and Password for that server. Filling in these
    three fields (plus the already filled in Server Port Number
    field = 445) works for me against my NAS.
  If you already tried this before, try it again at least once,
    just to see if it works this time. If it still doesn't work,
    then maybe something else is going on, and it may be worthwhile
    to capture debug logs like we've been discussing.
  Could you let us know whether the Search functionality works
    after rebooting your Chromebook, and whether manually entering
    the IP address (and username and password) for one of your
    servers works?
  If you'd like to capture logs for further troubleshooting, here
    are some suggestions.
  Take a new look at @yoichiro's
    instructions, particularly step 3:
  https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools
  Also, when he closed this bug, he said that if you can get
    further diagnostic info (e.g. a text copy or screenshot of the
    Console screen, as in Step 3 of the above link), you can open a
    new issue and provide that new diagnostic data, e.g. paste the
    text or attach the screenshot in your issue-opening comment. I
    suspect he won't be following this closed issue.

    More technical description follows:
    I suspect that the underlying root cause of the magnifying
      glass failure that I'm seeing is fixed in this Chrome patch
      for the chrome.mdns` API:
    https://chromium.googlesource.com/chromium/src/+/261ed0511eea1e3d10c5daa4dce563d1dfc7b5fc
    See also this bug report, which this patch says it addresses
      -- it seems to describe behavior similar to what I'm seeing:
      https://code.google.com/p/chromium/issues/detail?id=504477
    From what I can see, this patch is applied in Chrome version
      45 (and 46), but not version 44. So once v45 goes Stable, I
      suspect the SMB/CIFS app's magnifying glass may work more
      reliably.
    I'm not sure, but it might help if if @yoichiro adds functionality for
      the new forceDiscovery method documented here: https://developer.chrome.com/apps/mdns,
      which appears in v45.
    In order to see the chrome.mdns API in use in
      this SMB/CIFS app, I needed to first disable then re-enable
      this app in the chrome://extensions page, then click on the
      background page link, then open the console tab. Now there are
      one or more log entries regarding chrome.mdns at
      the top of the console.
    Now when I do this, I see that chrome.mdns is
      reporting my NAS to the app (and indeed it shows up when I
      click the magnifying glass):

    Before the reboot, I was only seeing the "Array[0]" line, not
      the "Array[1]" line, which indicates that chrome.mdns
      was not reporting to the app that my NAS was announcing itself
      using mDNS. In fact the NAS has been reporting its presence
      the whole time using mDNS, it's just that chrome.mdns
      wasn't telling the SMB/CIFS app about it. Again, I suspect
      this is fixed in Chrome 45.

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by dkewley** [comment] 2015-08-16 00:01
OK @des421 let's let this rest for now. If you speak up on this Github issue again, I'll hear it and do my best to respond.

One thing I'm realizing today: this SMB/CIFS app is using mDNS to find SMB shares, and this works both for your R7000-based NAS functionality, and my Synology NAS. Both of those SMB servers announce themselves using mDNS. But apparently Windows doesn't announce its SMB shares using mDNS (at least by default), so this app is not discovering those Windows shares. I see this (mis)behavior as well. No surprise it doesn't work, in retrospect. The Chrome 45 fix I mentioned won't fix this, since it's simply a fix to mDNS.

I'm not super clear on the details, but Windows has its own ages-old protocol for announcing and finding shares, and this app doesn't use that method. This is why we're not seeing our Windows shares. But you should still be able to connect to those shares by manually specifying the server IP address. This works for me to my Windows 7 box using this app.

In all cases, unless the share allows anonymous connection (and I'm not clear on how that works), you'll need a valid username and password that are allowed to use the shares. I suppose something is funny in this area with your attempts to connect to your R7000 share, though I'm not sure what exactly.

As for the R7000 versus ReadyNAS names, I wouldn't worry about that too much. I believe that's a difference in the name announced via mDNS versus the name announced by the Windows protocols. For the sake of this SMB/CIFS app, all that matters is that when you select "R7000", it fills in the correct IP address, which it sounds like does indeed happen.

Glad to hear the app's Search functionality found your R7000 (temporarily?) immediately after a reboot. It's nice to get verification I'm not the only one seeing this behavior. I still am hopefully that Chrome 45 will make this work more persistently, not just immediately after reboot.
