### ISSUE TITLE
NT_ACCESS_DENIED on Version 2.3.1 - Domain Account

### ISSUE THREAD

**Issue by rcoleman91** [yoichiro/chromeos-filesystem-cifs#136] opened 2015-10-14 01:02 UTC
Hi Yoichiro,
We are still receiving the NT_ACCESS_DENIED error when attempting to connect using a domain account on a server 2012 SMB share.
I have emailed the wireshark capture logs as Github does not support the file types.

Can confirm no issue when connecting from the ChromeOS client to a non-domain joined ubuntu share.

Regards,
Ryan

**Comment by yoichiro** [comment] 2015-10-14 01:10
@rcoleman91 Thank you for the feedback. I have already get logs from you via your email. Please give me a few days to investigate the logs and the cause.

**Comment by yoichiro** [comment] 2015-10-14 12:28
@rcoleman91 I checked the logs you sent to me. Actually, the packet sent from my apps to connect the tree (equals to shared resource) was rejected. And, the packets which communications were successfully have... for Kerberos authentication. I guess that shared resources you tried to access need the Kerberos authentication, and they reject the NTLM(v2) authentication. However, my app doesn't support the Kerberos authentication. As the result, you faced the NT_STATUS_ACCESS_DENIED error, I think.

Ryan, could you confirm that the shared resources can be accessed by users who are authenticated by NTLM(v2) as the server's setting?

**Comment by rcoleman91** [comment] 2015-10-15 00:10
Hi Yoichiro,
Can confirm NTLMv2 by viewing the event log on the machine that I am attempting to connect to the SMB share.
![ntlm event](https://cloud.githubusercontent.com/assets/14174034/10501438/6328a75e-732d-11e5-9fe0-a36cb2ca6639.PNG)

**Comment by rcoleman91** [comment] 2015-10-15 00:11
Can provide the event log if needed.

**Comment by yoichiro** [comment] 2015-10-20 00:53
@rcoleman91 Hmm... OK, I see. Actually, the authentication was successfully, but the next command was rejected from the Win Server.

As the one point, when your server returned the result of the negotiation, the security flag has "signature required: true". That is, perphaps, your server rejects all requests which don't have a signature. In fact, my app doesn't support the signature feature. Therefore, your server rejected the command of after negotiation/authentication, I guess...

**Comment by yoichiro** [comment] 2015-10-22 00:14
@rcoleman91 I don't start coding for supporting signature, but I found a bug. It was described at the following post: https://plus.google.com/u/0/+YoichiroTanaka/posts/EEJyicfnSqK I have already released a new version 2.4.0 including code to fix the problem.

Perphaps, the version 2.4.0 will not be able to solve the problem reported by you, I guess. But, could you confirm whether or not the new version works on your environment?

**Comment by rcoleman91** [comment] 2015-10-22 01:22
@yoichiro Looks like you have done something very right! App is working well. I am able to mount our file server and open files directly from the app. Security is also followed with my test account unable to see any files it does not have security permissions to access.

**Comment by yoichiro** [comment] 2015-10-22 02:42
@rcoleman91 Wow! It's nice news to me and all users. Thank you for this feedback. I could fix a big problem by your contribution. You can close this issue.

**Closed as completed** 2015-10-22 02:45 UTC
