### ISSUE TITLE
NT_STATUS_OBJECT PATH NOT FOUND Problem

### ISSUE THREAD

**Issue by Carl393** [yoichiro/chromeos-filesystem-cifs#99] opened 2015-08-31 06:25 UTC
I am having a problem using an Apple Airport Hardware and Hard Drive connected to it

When I mount the filesystem (the IP address that is the Apple Airport) File System finds the name of the hard drive... I select it... it then says.. Successfully Mounted then this error happens..

"NT_STATUS_OBJECT PATH NOT FOUND"

Do I have to enable something in the apple airport utility for this to work properly? thank you.

**Comment by yoichiro** [comment] 2015-09-03 11:42
@Carl393 Basically, its error would occur when you enter a wrong shared resource name, I guess. When you can reproduce this issue, could you report the output logs on the DevTools Console tab to me by the following steps?
https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by yoichiro** [comment] 2015-09-18 13:44
I close this issue, because I could not get more information to fix this issue from the reporter. Sorry.

**Closed as completed by yoichiro** 2015-09-18 13:44 UTC

**Comment by Carl393** [comment] 2015-09-18 17:26
```
                                                                                  Sorry I am very busy as I run a business I can't do it right now                                                                                                                                                                                                                                                                                                                                        Carl                                                                                                                                                                                                                From: Yoichiro TanakaSent: Friday, September 18, 2015 9:44 AMTo: yoichiro/chromeos-filesystem-cifsReply To: yoichiro/chromeos-filesystem-cifsCc: Carl393Subject: Re: [chromeos-filesystem-cifs] NT_STATUS_OBJECT PATH NOT FOUND Problem (#99)I close this issue, because I could not get more information to fix this issue from the reporter. Sorry.
```

—Reply to this email directly or view it on GitHub.
