### ISSUE TITLE
Still have readyshare problems ....

### ISSUE THREAD

**Issue by WillemChromebook** [yoichiro/chromeos-filesystem-cifs#128] opened 2015-09-25 23:57 UTC
With reference to closed item 121 (I did not close it) the following.

I tried the examples shown in the
screenshots (I got new router and had to change IP address) and I did not
succeed to mount readyshare.
When using the IP address (without smb:\) the first two examples geve the
error message NT status access denied. When using readyshare (without
smb:\) the last two examples gave the error message name not resolved.

I hope this helps to diagnose the problem

Willem

**Comment by WillemChromebook** [comment] 2015-09-26 18:13
I connected with my modem and got the following information about readyshare. Maybe this will help to solve the problem.

![screenshot 2015-09-26 at 14 09 38 - display 1](https://cloud.githubusercontent.com/assets/13853656/10119045/b95fd5a4-6458-11e5-84c9-6507566fb93e.png)

**Comment by yoichiro** [comment] 2015-10-13 01:20
@WillemChromebook Probably, I found the cause of this problem. Please see: https://github.com/yoichiro/chromeos-filesystem-cifs/issues/109#issuecomment-147560322

**Comment by yoichiro** [comment] 2015-10-13 14:53
@WillemChromebook I have just released a new version 2.3.1. This version includes the modification about User ID problem. Could you test the version on your environment?

**Comment by didtoknan** [comment] 2015-10-13 16:06
I guess Willem will be as happy as I am, because it works now ! Thanks again.

**Comment by yoichiro** [comment] 2015-10-13 22:08
@didtoknan OK, thank you for the confirmation.
@WillemChromebook Probably, you can acccess to your server with the latest version. I close this issue. Thank you for this feedback.

**Closed as completed by yoichiro** 2015-10-13 22:08 UTC

**Comment by oogunlegan** [comment] 2015-12-02 01:58
I'm having issues mounting my server and getting the same NT STATUS error that as posted earlier in this post.  

I believe I have the most recent version of the app, I just d/l it 2 days ago.  

Any help would be wonderful
