### ISSUE TITLE
"Some operations are taking longer than expected"

### ISSUE THREAD

**Issue by aj465** [yoichiro/chromeos-filesystem-cifs#139] opened 2015-10-18 10:53 UTC
I am getting the "Some operations are taking longer than expected" error frequently very since recent updates. Attached are some logs whilst trying to copy some files, which performs very slowly. The Files app seems to stop responding.

![screenshot 2015-10-18 at 11 50 08](https://cloud.githubusercontent.com/assets/12121944/10563748/66781044-758e-11e5-98d5-5ccf78650cdf.png)

**Comment by aj465** [comment] 2015-10-18 12:02
To explain a little more, this occurred whilst dragging and dropping files into Chrome to upload. I've noticed that once the Files app is closed, these errors eventually stop and my copy (upload) seems to continue more successfully.

**Comment by yoichiro** [comment] 2015-11-01 21:41
It seems that this issue is same as #144. As the difference, this issue can be represented in the case of connecting with SMB1.

**Comment by yoichiro** [comment] 2015-11-01 22:04
Fixed this issue on #147

**Comment by yoichiro** [comment] 2015-11-01 22:31
@aj465 I have released a new version 2.6.1 including code to fix this issue. Could you confirm whether or not this issue is reproduced?

**Comment by yoichiro** [comment] 2015-11-06 11:47
I close this issue, because finally I could not receive any feedbacks from @aj465.

**Closed as completed by yoichiro** 2015-11-06 11:47 UTC
Labels: bug
