### ISSUE TITLE
Fail to mount the SMB from my provider box, error 3221225506

### ISSUE THREAD

**Issue by nemolivier** [yoichiro/chromeos-filesystem-cifs#35] opened 2015-06-06 17:35 UTC
Hello,

My box provider can act as a NAS (both on the internal DD and external DD on USB). It works without problems with smb client on linux / windows / android
Settings are : 192.168.0.254 port 445 login/user
Here is the output : 

```
NTLMSSP_NEGOTIATE_UNICODE: true                      background.js:6170 
NTLMSSP_NEGOTIATE_OEM: false                            background.js:6170 
NTLMSSP_REQUEST_TARGET: true                          background.js:6170
NTLMSSP_NEGOTIATE_SIGN: false                            background.js:6170 
NTLMSSP_NEGOTIATE_SEAL: false                           background.js:6170 
NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false   background.js:6170 
NTLMSSP_NEGOTIATE_LM_KEY: false                      background.js:6170 
NTLMSSP_NEGOTIATE_NETWARE: false                   background.js:6170 
NTLMSSP_NEGOTIATE_NTLM: true                            background.js:6170 
NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false               background.js:6170 
NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false   background.js:6170 
NTLMSSP_NEGOTIATE_LOCAL_CALL: false              background.js:6170 
NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false            background.js:6170 
NTLMSSP_TARGET_TYPE_DOMAIN: false                  background.js:6170 
NTLMSSP_TARGET_TYPE_SERVER: true                  background.js:6170 
NTLMSSP_TARGET_TYPE_SHARE: false                   background.js:6170 
NTLMSSP_NEGOTIATE_NTLM2: true                          background.js:6170 
NTLMSSP_REQUEST_INIT_RESPONSE: false             background.js:6170 
NTLMSSP_REQUEST_ACCEPT_RESPONSE: false     background.js:6170 
NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false                   background.js:6170 
NTLMSSP_NEGOTIATE_TARGET_INFO: true              background.js:6170 
NTLMSSP_NEGOTIATE_128: true                                background.js:6170 
NTLMSSP_NEGOTIATE_KEY_EXCH: false                   background.js:6170 
NTLMSSP_NEGOTIATE_56: false                                 background.js:6170 
3221225506: NT_STATUS_ACCESS_DENIED             background.js:11816
```

Many many thanks for this extension, I've been waiting it for ages and can't thanks you enough for this (it will be better when VLC for chromebook will be out :))

**Comment by yoichiro** [comment] 2015-06-06 21:46
@nemolivier I just released a new version 1.1.6. When you update this app to 1.1.6, you can get more detail log output. Could you confirm the output again?

**Comment by nemolivier** [comment] 2015-06-06 22:33
Here it is, it's the "Trace" log level.

```
background.js:6156 Client#login
background.js:6156 connect
background.js:6163 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 47}
background.js:6156 writePacket
background.js:6156 readPacket
background.js:6156 _readPacketSize
background.js:6156 _readPacketSize - 2
background.js:6156 readPacket: 127
background.js:6163 Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
background.js:6163 NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 3, maxMpxCount_: 50, maxNumberVCs_: 1…}
background.js:6163 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160}
background.js:6156 writePacket
background.js:6156 readPacket
background.js:6156 _readPacketSize
background.js:6156 _readPacketSize - 2
background.js:6156 readPacket: 210
background.js:6170 NTLMSSP_NEGOTIATE_UNICODE: true
background.js:6170 NTLMSSP_NEGOTIATE_OEM: false
background.js:6170 NTLMSSP_REQUEST_TARGET: true
background.js:6170 NTLMSSP_NEGOTIATE_SIGN: false
background.js:6170 NTLMSSP_NEGOTIATE_SEAL: false
background.js:6170 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
background.js:6170 NTLMSSP_NEGOTIATE_LM_KEY: false
background.js:6170 NTLMSSP_NEGOTIATE_NETWARE: false
background.js:6170 NTLMSSP_NEGOTIATE_NTLM: true
background.js:6170 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
background.js:6170 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
background.js:6170 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
background.js:6170 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
background.js:6170 NTLMSSP_TARGET_TYPE_DOMAIN: false
background.js:6170 NTLMSSP_TARGET_TYPE_SERVER: true
background.js:6170 NTLMSSP_TARGET_TYPE_SHARE: false
background.js:6170 NTLMSSP_NEGOTIATE_NTLM2: true
background.js:6170 NTLMSSP_REQUEST_INIT_RESPONSE: false
background.js:6170 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
background.js:6170 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
background.js:6170 NTLMSSP_NEGOTIATE_TARGET_INFO: true
background.js:6170 NTLMSSP_NEGOTIATE_128: true
background.js:6170 NTLMSSP_NEGOTIATE_KEY_EXCH: false
background.js:6170 NTLMSSP_NEGOTIATE_56: false
background.js:6163 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 336}
background.js:6156 writePacket
background.js:6156 readPacket
background.js:6156 _readPacketSize
background.js:6156 _readPacketSize - 2
background.js:6156 readPacket: 100
background.js:6156 Client#getSharedResourceList
background.js:6163 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 92}
background.js:6156 writePacket
background.js:6156 readPacket
background.js:6156 _readPacketSize
background.js:6156 _readPacketSize - 2
background.js:6156 readPacket: 35
background.js:11816 3221225506: NT_STATUS_ACCESS_DENIED
```

**Comment by yoichiro** [comment] 2015-06-06 23:00
@nemolivier Hmm... You rejected the logon to your smb server, because there was "NT_STATUS_ACCESS_DENIED". I could NOT know the reason, because I can't check the server log of your smb server. You should check the server log, is it possible? If no, I think that this issue woud not be able to fix.

**Comment by nemolivier** [comment] 2015-06-07 07:21
I've dig in the server settings but can't find any logs :( I've try removing login/password access on the server, but it failed the same way.

```
background.js:6156 Object {type: "getSharedResources", serverName: "192.168.0.254", serverPort: "445", username: "", password: ""}
background.js:6156 Client#login
background.js:6156 connect
background.js:6163 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 47}
background.js:6156 writePacket
background.js:6156 readPacket
background.js:6156 _readPacketSize
background.js:6156 _readPacketSize - 2
background.js:6156 readPacket: 127
background.js:6163 Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}
background.js:6163 NegotiateProtocolResponse {types_: Types, dialectIndex_: 0, securityMode_: 3, maxMpxCount_: 50, maxNumberVCs_: 1…}
background.js:6163 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 160}
background.js:6156 writePacket
background.js:6156 readPacket
background.js:6156 _readPacketSize
background.js:6156 _readPacketSize - 2
background.js:6156 readPacket: 252
background.js:6170 NTLMSSP_NEGOTIATE_UNICODE: true
background.js:6170 NTLMSSP_NEGOTIATE_OEM: false
background.js:6170 NTLMSSP_REQUEST_TARGET: true
background.js:6170 NTLMSSP_NEGOTIATE_SIGN: false
background.js:6170 NTLMSSP_NEGOTIATE_SEAL: false
background.js:6170 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
background.js:6170 NTLMSSP_NEGOTIATE_LM_KEY: false
background.js:6170 NTLMSSP_NEGOTIATE_NETWARE: false
background.js:6170 NTLMSSP_NEGOTIATE_NTLM: true
background.js:6170 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
background.js:6170 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
background.js:6170 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
background.js:6170 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
background.js:6170 NTLMSSP_TARGET_TYPE_DOMAIN: false
background.js:6170 NTLMSSP_TARGET_TYPE_SERVER: true
background.js:6170 NTLMSSP_TARGET_TYPE_SHARE: false
background.js:6170 NTLMSSP_NEGOTIATE_NTLM2: true
background.js:6170 NTLMSSP_REQUEST_INIT_RESPONSE: false
background.js:6170 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
background.js:6170 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
background.js:6170 NTLMSSP_NEGOTIATE_TARGET_INFO: true
background.js:6170 NTLMSSP_NEGOTIATE_128: true
background.js:6170 NTLMSSP_NEGOTIATE_KEY_EXCH: false
background.js:6170 NTLMSSP_NEGOTIATE_56: false
background.js:6163 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 350}dataLength_: 350data_: ArrayBufferbyteLength: (...)__proto__: ArrayBufferbyteLength: (...)get byteLength: byteLength() { [native code] }arguments: (...)get arguments: ThrowTypeError() { [native code] }arguments: nullcaller: nulllength: 0name: "ThrowTypeError"prototype: ThrowTypeErrorconstructor: ThrowTypeError() { [native code] }arguments: nullcaller: nulllength: 0name: "ThrowTypeError"prototype: ThrowTypeErrorconstructor: ThrowTypeError() { [native code] }arguments: nullcaller: nulllength: 0name: "ThrowTypeError"prototype: ThrowTypeErrorconstructor: ThrowTypeError() { [native code] }arguments: nullcaller: nulllength: 0name: "ThrowTypeError"prototype: ThrowTypeError__proto__: Empty() {}<function scope>__proto__: Object__defineGetter__: __defineGetter__() { [native code] }__defineSetter__: __defineSetter__() { [native code] }__lookupGetter__: __lookupGetter__() { [native code] }__lookupSetter__: __lookupSetter__() { [native code] }constructor: Object() { [native code] }hasOwnProperty: hasOwnProperty() { [native code] }isPrototypeOf: isPrototypeOf() { [native code] }propertyIsEnumerable: propertyIsEnumerable() { [native code] }toLocaleString: toLocaleString() { [native code] }toString: toString() { [native code] }valueOf: valueOf() { [native code] }get __proto__: __proto__() { [native code] }set __proto__: __proto__() { [native code] }__proto__: Empty() {}<function scope>__proto__: Object__defineGetter__: __defineGetter__() { [native code] }__defineSetter__: __defineSetter__() { [native code] }__lookupGetter__: __lookupGetter__() { [native code] }__lookupSetter__: __lookupSetter__() { [native code] }constructor: Object() { [native code] }hasOwnProperty: hasOwnProperty() { [native code] }isPrototypeOf: isPrototypeOf() { [native code] }propertyIsEnumerable: propertyIsEnumerable() { [native code] }toLocaleString: toLocaleString() { [native code] }toString: toString() { [native code] }valueOf: valueOf() { [native code] }get __proto__: __proto__() { [native code] }set __proto__: __proto__() { [native code] }__proto__: Empty() {}apply: apply() { [native code] }arguments: nullbind: bind() { [native code] }call: call() { [native code] }caller: nullconstructor: Function() { [native code] }length: 0name: "Empty"toString: toString() { [native code] }__proto__: Object<function scope><function scope>__proto__: Object__proto__: Empty() {}<function scope>set arguments: ThrowTypeError() { [native code] }caller: (...)get caller: ThrowTypeError() { [native code] }set caller: ThrowTypeError() { [native code] }length: 0name: "byteLength"__proto__: Empty() {}<function scope>constructor: ArrayBuffer() { [native code] }slice: slice() { [native code] }Symbol(Symbol.toStringTag): "ArrayBuffer"__proto__: Objecttypes_: Types__proto__: Packet
background.js:6156 writePacket
background.js:6156 readPacket
background.js:6156 _readPacketSize
background.js:6156 _readPacketSize - 2
background.js:6156 readPacket: 100
background.js:6156 Client#getSharedResourceList
background.js:6163 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 92}
background.js:6156 writePacket
background.js:6156 readPacket
background.js:6156 _readPacketSize
background.js:6156 _readPacketSize - 2
background.js:6156 readPacket: 35
background.js:11816 3221225506: NT_STATUS_ACCESS_DENIED
```

In this log from chrome dev tools there's a lot of « branch » that I don't open (it will make a huge tree, and I can't imagine the time to open them all :)) And I can't find a " save logs" option.
Tell me if you need me to do it.
In the server settings, I can set a workgroup, and it's often this name that is find by the auto-setup in windows, linux or android. This field is set on "WORKGOUP" by default.

I understand that you can't go further without logs… thanks for taking time on this, maybe future update will help me to use your work !

**Comment by hvdwolf** [comment] 2015-06-07 12:43
Please have a look at issue https://github.com/yoichiro/chromeos-filesystem-cifs/issues/40 and of the 3 last messages of issue https://github.com/yoichiro/chromeos-filesystem-cifs/issues/32.

Please try without username and password. I bet you have one or more public shares mixed with one or more user/password protected shares.

**Comment by yoichiro** [comment] 2015-06-07 13:08
@hvdwolf Without username and password? What's meaning?

**Comment by hvdwolf** [comment] 2015-06-07 14:19
If you don't specify a username and password it does a real browse for shared services. When specifying a username/password I assume you get a mixed answer.

As mentioned in "my issue"  https://github.com/yoichiro/chromeos-filesystem-cifs/issues/40 I get a response with possible shares if I leave the username and password empty.
If I do specify a username and password I get the error.

**Comment by nemolivier** [comment] 2015-06-07 20:20
I'm not shure my server provide multiple settings shares (but it could be used internally, without allowing me to know).
But as I wrote above, I've tried allowing all access (no login/password but you need to be on the local network). Logs are above, same error.

**Comment by nemolivier** [comment] 2015-06-08 12:48
I haven't close this! Have-I? I'm not used to Github...

**Comment by hvdwolf** [comment] 2015-06-08 13:11
I think you pressed "Comment and Close" instead of "Comment". You can reopen it as well.

With regard to "but you need to be on the local network": I assume your firewall is closed for port 445 and 139. You have to be careful whether you want to expose your shares to the outside world.

**Comment by nemolivier** [comment] 2015-06-08 13:23
Thanks, do you want me to re-open it or you is it closed for you ?

**Comment by hvdwolf** [comment] 2015-06-08 13:26
If your issue is satisfactory solved and no users with the same issue are using the same ticket (not in this case), you can leave it closed.

**Comment by nemolivier** [comment] 2015-06-08 13:45
My issue is not solved... Since it's the first time I can't connect to this SMB share, I may keep it open.

**Comment by yoichiro** [comment] 2015-06-26 01:33
@nemolivier I have released a new version 1.4.3. Could you confirm whether the latest version works on your environment or not? If this issue reproduced, could you describe the detail steps to be able to reproduce by everyone?

**Comment by nemolivier** [comment] 2015-06-26 19:23
hello,
no, it don't :(
Trying to log with manually filling setting give me error #3221225581 NT_STATUS_LOGON_FAILURE
And the « search » fonction still give me nothing (It works on all smb client in windows/linux/android).

**Comment by nemolivier** [comment] 2015-06-26 19:24
Hum… strange : if I use the recorded smb share, I have the 3221225581 error, but if I create a new one, I get the 3221225506 error.
Do you want more precise logs ?

**Comment by StarrWulfe** [comment] 2015-07-08 16:20
I'm getting the same thing exactly from my Buffalo Cloudstor as well. However I have a Raspberry Pi with XBMC/Kodi running on it and I can connect to it just fine.

**Comment by yoichiro** [comment] 2015-08-10 08:41
I close this issue, because this issue has many error cases. Therefore, I cannot treat each issue here.
If you have an issue, please create a new issue WITH A DEBUG LOG by the following steps:
https://github.com/yoichiro/chromeos-filesystem-cifs/wiki/How-to-Capture-the-Console-Log-of-DevTools

Thank you for your reporting.

**Closed as completed by yoichiro** 2015-08-10 08:41 UTC

**Comment by johnmark** [comment] 2015-10-08 16:42
Seems like all of these errors are reported by people connecting to storage servers running some version of Samba on Linux. In my case, it's a Netgear Stora. I'll follow the instructions above to report my error. Thanks.

**Comment by nemolivier** [comment] 2015-10-23 19:39
Last update finaly solve this issue \o/ 
I can mount my smb share and even look at a movie from it. 
Thank's a lot !

**Comment by johnmark** [comment] 2015-10-23 21:52
Same here! I've had no problems for the last 2 weeks.
