### ISSUE TITLE
v 2.0.2 NT_STATUS_INVALID_PARAMETER

### ISSUE THREAD

**Issue by cottonwool** [yoichiro/chromeos-filesystem-cifs#104] opened 2015-09-04 13:02 UTC
When I try to connect to my PC in the usual way I now get the following error and no connection.

SMB/CIFS File System
c000000d:
NT_STATUS_INVALID_PARAMETER

Console log follows

background.js:18374 Looked up with chrome.mdns:  Array[0]length: 0__proto__: Array[0]
background.js:18374 Looked up with chrome.mdns:  Array[0]length: 0__proto__: Array[0]
background.js:6379 Domain name not specified. '?' will be applied.
background.js:6372 connect
background.js:6372 Header {types_: Types, protocol_: "SMB", command_: 114, errorClass_: 0, errorCode_: 0…}command_: 114errorClass_: 0errorCode_: 0flag2_: 51203flag_: 24multiplexId_: 1ntStyleErrorCode_: 0processId_: 1protocol_: "SMB"treeId_: 0types_: TypesuserId_: 0__proto__: Header
background.js:6372 NegotiateProtocolRequest {types_: Types, dialects: Array[0], dialects_: Array[2]}dialects: Array[0]dialects_: Array[2]types_: Types__proto__: NegotiateProtocolRequest
background.js:6372 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 58, packetHelper_: PacketHelper}dataLength_: 58data_: ArrayBufferpacketHelper_: PacketHelpertypes_: Types__proto__: Packet
background.js:6379 Negotiated with SMB2
background.js:6372 Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 0, channelSequence_: 0…}chainOffset_: 0channelSequence_: 0command_: 0creditCharge_: 0creditsGranted_: 1creditsRequested_: 1flags_: 1messageId_: 0processId_: 0protocol_: "SMB"sessionId_: 0signature_: Uint8Array[16]status_: 0structureSize_: 64treeId_: 0types_: Types__proto__: Header
background.js:6372 NegotiateResponse {types_: Types, structureSize_: 65, securityMode_: 1, dialectRevision_: 514, serverGuid_: "h�d��!8B�X{#�:�"…}buffer_: Uint8Array[42]capabilities_: 1dialectRevision_: 514maxReadSize_: 65536maxTransaction_: 65536maxWriteSize_: 65536securityBufferLength_: 42securityBufferOffset_: 128securityMode_: 1serverGuid_: "h�d��!8B�X{#�:�"serverStartTime_: Fri Sep 04 2015 00:56:42 GMT+0100 (BST)structureSize_: 65systemTime_: Fri Sep 04 2015 13:16:59 GMT+0100 (BST)types_: Types__proto__: NegotiateResponse
background.js:6372 Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}chainOffset_: 0channelSequence_: 0command_: 1creditCharge_: 1creditsGranted_: 0creditsRequested_: 1flags_: 0messageId_: 1processId_: 1protocol_: "SMB"sessionId_: 0signature_: 0status_: 0structureSize_: 64treeId_: 0types_: Types__proto__: Header
background.js:6372 SessionSetupRequest {types_: Types, flags_: 0, securityMode_: 1, capabilities_: 1, channel_: 0…}capabilities_: 1channel_: 0flags_: 0previousSessionId_: ""securityBlobLength_: 41securityBlobOffset_: nullsecurityBlob_: ArrayBuffersecurityMode_: 1types_: Types__proto__: SessionSetupRequest
background.js:6372 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 129, packetHelper_: PacketHelper}dataLength_: 129data_: ArrayBufferpacketHelper_: PacketHelpertypes_: Types__proto__: Packet
background.js:6372 Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 22…}chainOffset_: 0channelSequence_: 22command_: 1creditCharge_: 1creditsGranted_: 1creditsRequested_: 1flags_: 1messageId_: 1processId_: 1protocol_: "SMB"sessionId_: 4398046511125signature_: Uint8Array[16]status_: 3221225494structureSize_: 64treeId_: 0types_: Types__proto__: Header
background.js:6379 NTLMSSP_NEGOTIATE_UNICODE: true
background.js:6379 NTLMSSP_NEGOTIATE_OEM: false
background.js:6379 NTLMSSP_REQUEST_TARGET: true
background.js:6379 NTLMSSP_NEGOTIATE_SIGN: false
background.js:6379 NTLMSSP_NEGOTIATE_SEAL: false
background.js:6379 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
background.js:6379 NTLMSSP_NEGOTIATE_LM_KEY: false
background.js:6379 NTLMSSP_NEGOTIATE_NETWARE: false
background.js:6379 NTLMSSP_NEGOTIATE_NTLM: true
background.js:6379 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
background.js:6379 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
background.js:6379 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
background.js:6379 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
background.js:6379 NTLMSSP_TARGET_TYPE_DOMAIN: false
background.js:6379 NTLMSSP_TARGET_TYPE_SERVER: true
background.js:6379 NTLMSSP_TARGET_TYPE_SHARE: false
background.js:6379 NTLMSSP_NEGOTIATE_NTLM2: true
background.js:6379 NTLMSSP_REQUEST_INIT_RESPONSE: false
background.js:6379 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
background.js:6379 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
background.js:6379 NTLMSSP_NEGOTIATE_TARGET_INFO: true
background.js:6379 NTLMSSP_NEGOTIATE_128: true
background.js:6379 NTLMSSP_NEGOTIATE_KEY_EXCH: false
background.js:6379 NTLMSSP_NEGOTIATE_56: false
background.js:6372 Header {types_: Types, protocol_: "SMB", structureSize_: 64, creditCharge_: 1, channelSequence_: 0…}
background.js:6372 SessionSetupRequest {types_: Types, flags_: 0, securityMode_: 1, capabilities_: 1, channel_: 0…}
background.js:6372 Packet {types_: Types, data_: ArrayBuffer, dataLength_: 330, packetHelper_: PacketHelper}

**Comment by cottonwool** [comment] 2015-09-04 13:09
This is what Wireshark sees on port 445.
See Frame 13 in particular.

No.     Time           Source                Destination           Protocol Length Info
      1 0.000000000    192.168.178.1         192.168.178.20        NBSS     60     Session keep-alive

Frame 1: 60 bytes on wire (480 bits), 60 bytes captured (480 bits) on interface 0
Ethernet II, Src: Avm_3c:ae:eb (9c:c7:a6:3c:ae:eb), Dst: IntelCor_f7:53:65 (00:1c:c0:f7:53:65)
Internet Protocol Version 4, Src: 192.168.178.1 (192.168.178.1), Dst: 192.168.178.20 (192.168.178.20)
Transmission Control Protocol, Src Port: 445 (445), Dst Port: 52503 (52503), Seq: 1, Ack: 1, Len: 4
NetBIOS Session Service

No.     Time           Source                Destination           Protocol Length Info
      2 0.210401000    192.168.178.20        192.168.178.1         TCP      54     52503→445 [ACK] Seq=1 Ack=5 Win=16211 Len=0

Frame 2: 54 bytes on wire (432 bits), 54 bytes captured (432 bits) on interface 0
Ethernet II, Src: IntelCor_f7:53:65 (00:1c:c0:f7:53:65), Dst: Avm_3c:ae:eb (9c:c7:a6:3c:ae:eb)
Internet Protocol Version 4, Src: 192.168.178.20 (192.168.178.20), Dst: 192.168.178.1 (192.168.178.1)
Transmission Control Protocol, Src Port: 52503 (52503), Dst Port: 445 (445), Seq: 1, Ack: 5, Len: 0

No.     Time           Source                Destination           Protocol Length Info
      3 44.098888000   192.168.178.22        192.168.178.20        TCP      74     34671→445 [SYN] Seq=0 Win=14600 Len=0 MSS=1460 SACK_PERM=1 TSval=704903 TSecr=0 WS=128

Frame 3: 74 bytes on wire (592 bits), 74 bytes captured (592 bits) on interface 0
Ethernet II, Src: HonHaiPr_a1:9e:e3 (14:2d:27:a1:9e:e3), Dst: IntelCor_f7:53:65 (00:1c:c0:f7:53:65)
Internet Protocol Version 4, Src: 192.168.178.22 (192.168.178.22), Dst: 192.168.178.20 (192.168.178.20)
Transmission Control Protocol, Src Port: 34671 (34671), Dst Port: 445 (445), Seq: 0, Len: 0

No.     Time           Source                Destination           Protocol Length Info
      4 44.101362000   192.168.178.20        192.168.178.22        TCP      74     445→34671 [SYN, ACK] Seq=0 Ack=1 Win=8192 Len=0 MSS=1460 WS=256 SACK_PERM=1 TSval=4539585 TSecr=704903

Frame 4: 74 bytes on wire (592 bits), 74 bytes captured (592 bits) on interface 0
Ethernet II, Src: IntelCor_f7:53:65 (00:1c:c0:f7:53:65), Dst: HonHaiPr_a1:9e:e3 (14:2d:27:a1:9e:e3)
Internet Protocol Version 4, Src: 192.168.178.20 (192.168.178.20), Dst: 192.168.178.22 (192.168.178.22)
Transmission Control Protocol, Src Port: 445 (445), Dst Port: 34671 (34671), Seq: 0, Ack: 1, Len: 0

No.     Time           Source                Destination           Protocol Length Info
      5 44.103565000   192.168.178.22        192.168.178.20        TCP      66     34671→445 [ACK] Seq=1 Ack=1 Win=14720 Len=0 TSval=704909 TSecr=4539585

Frame 5: 66 bytes on wire (528 bits), 66 bytes captured (528 bits) on interface 0
Ethernet II, Src: HonHaiPr_a1:9e:e3 (14:2d:27:a1:9e:e3), Dst: IntelCor_f7:53:65 (00:1c:c0:f7:53:65)
Internet Protocol Version 4, Src: 192.168.178.22 (192.168.178.22), Dst: 192.168.178.20 (192.168.178.20)
Transmission Control Protocol, Src Port: 34671 (34671), Dst Port: 445 (445), Seq: 1, Ack: 1, Len: 0

No.     Time           Source                Destination           Protocol Length Info
      6 44.116810000   192.168.178.22        192.168.178.20        SMB      128    Negotiate Protocol Request

Frame 6: 128 bytes on wire (1024 bits), 128 bytes captured (1024 bits) on interface 0
Ethernet II, Src: HonHaiPr_a1:9e:e3 (14:2d:27:a1:9e:e3), Dst: IntelCor_f7:53:65 (00:1c:c0:f7:53:65)
Internet Protocol Version 4, Src: 192.168.178.22 (192.168.178.22), Dst: 192.168.178.20 (192.168.178.20)
Transmission Control Protocol, Src Port: 34671 (34671), Dst Port: 445 (445), Seq: 1, Ack: 1, Len: 62
NetBIOS Session Service
SMB (Server Message Block Protocol)

No.     Time           Source                Destination           Protocol Length Info
      7 44.117519000   192.168.178.20        192.168.178.22        SMB2     240    Negotiate Protocol Response

Frame 7: 240 bytes on wire (1920 bits), 240 bytes captured (1920 bits) on interface 0
Ethernet II, Src: IntelCor_f7:53:65 (00:1c:c0:f7:53:65), Dst: HonHaiPr_a1:9e:e3 (14:2d:27:a1:9e:e3)
Internet Protocol Version 4, Src: 192.168.178.20 (192.168.178.20), Dst: 192.168.178.22 (192.168.178.22)
Transmission Control Protocol, Src Port: 445 (445), Dst Port: 34671 (34671), Seq: 1, Ack: 63, Len: 174
NetBIOS Session Service
SMB2 (Server Message Block Protocol version 2)

No.     Time           Source                Destination           Protocol Length Info
      8 44.119664000   192.168.178.22        192.168.178.20        TCP      66     34671→445 [ACK] Seq=63 Ack=175 Win=15744 Len=0 TSval=704926 TSecr=4539587

Frame 8: 66 bytes on wire (528 bits), 66 bytes captured (528 bits) on interface 0
Ethernet II, Src: HonHaiPr_a1:9e:e3 (14:2d:27:a1:9e:e3), Dst: IntelCor_f7:53:65 (00:1c:c0:f7:53:65)
Internet Protocol Version 4, Src: 192.168.178.22 (192.168.178.22), Dst: 192.168.178.20 (192.168.178.20)
Transmission Control Protocol, Src Port: 34671 (34671), Dst Port: 445 (445), Seq: 63, Ack: 175, Len: 0

No.     Time           Source                Destination           Protocol Length Info
      9 44.152430000   192.168.178.22        192.168.178.20        SMB2     199    Session Setup Request, NTLMSSP_NEGOTIATE

Frame 9: 199 bytes on wire (1592 bits), 199 bytes captured (1592 bits) on interface 0
Ethernet II, Src: HonHaiPr_a1:9e:e3 (14:2d:27:a1:9e:e3), Dst: IntelCor_f7:53:65 (00:1c:c0:f7:53:65)
Internet Protocol Version 4, Src: 192.168.178.22 (192.168.178.22), Dst: 192.168.178.20 (192.168.178.20)
Transmission Control Protocol, Src Port: 34671 (34671), Dst Port: 445 (445), Seq: 63, Ack: 175, Len: 133
NetBIOS Session Service
SMB2 (Server Message Block Protocol version 2)

No.     Time           Source                Destination           Protocol Length Info
     10 44.152709000   192.168.178.20        192.168.178.22        SMB2     300    Session Setup Response, Error: STATUS_MORE_PROCESSING_REQUIRED, NTLMSSP_CHALLENGE

Frame 10: 300 bytes on wire (2400 bits), 300 bytes captured (2400 bits) on interface 0
Ethernet II, Src: IntelCor_f7:53:65 (00:1c:c0:f7:53:65), Dst: HonHaiPr_a1:9e:e3 (14:2d:27:a1:9e:e3)
Internet Protocol Version 4, Src: 192.168.178.20 (192.168.178.20), Dst: 192.168.178.22 (192.168.178.22)
Transmission Control Protocol, Src Port: 445 (445), Dst Port: 34671 (34671), Seq: 175, Ack: 196, Len: 234
NetBIOS Session Service
SMB2 (Server Message Block Protocol version 2)

No.     Time           Source                Destination           Protocol Length Info
     11 44.194407000   192.168.178.22        192.168.178.20        TCP      66     34671→445 [ACK] Seq=196 Ack=409 Win=16768 Len=0 TSval=705001 TSecr=4539590

Frame 11: 66 bytes on wire (528 bits), 66 bytes captured (528 bits) on interface 0
Ethernet II, Src: HonHaiPr_a1:9e:e3 (14:2d:27:a1:9e:e3), Dst: IntelCor_f7:53:65 (00:1c:c0:f7:53:65)
Internet Protocol Version 4, Src: 192.168.178.22 (192.168.178.22), Dst: 192.168.178.20 (192.168.178.20)
Transmission Control Protocol, Src Port: 34671 (34671), Dst Port: 445 (445), Seq: 196, Ack: 409, Len: 0

No.     Time           Source                Destination           Protocol Length Info
     12 44.228508000   192.168.178.22        192.168.178.20        SMB2     400    Session Setup Request, NTLMSSP_AUTH, User: ?\mark

Frame 12: 400 bytes on wire (3200 bits), 400 bytes captured (3200 bits) on interface 0
Ethernet II, Src: HonHaiPr_a1:9e:e3 (14:2d:27:a1:9e:e3), Dst: IntelCor_f7:53:65 (00:1c:c0:f7:53:65)
Internet Protocol Version 4, Src: 192.168.178.22 (192.168.178.22), Dst: 192.168.178.20 (192.168.178.20)
Transmission Control Protocol, Src Port: 34671 (34671), Dst Port: 445 (445), Seq: 196, Ack: 409, Len: 334
NetBIOS Session Service
SMB2 (Server Message Block Protocol version 2)

No.     Time           Source                Destination           Protocol Length Info
     13 44.228887000   192.168.178.20        192.168.178.22        SMB2     143    Session Setup Response, Error: STATUS_INVALID_PARAMETER

Frame 13: 143 bytes on wire (1144 bits), 143 bytes captured (1144 bits) on interface 0
Ethernet II, Src: IntelCor_f7:53:65 (00:1c:c0:f7:53:65), Dst: HonHaiPr_a1:9e:e3 (14:2d:27:a1:9e:e3)
Internet Protocol Version 4, Src: 192.168.178.20 (192.168.178.20), Dst: 192.168.178.22 (192.168.178.22)
Transmission Control Protocol, Src Port: 445 (445), Dst Port: 34671 (34671), Seq: 409, Ack: 530, Len: 77
NetBIOS Session Service
SMB2 (Server Message Block Protocol version 2)

No.     Time           Source                Destination           Protocol Length Info
     14 44.230843000   192.168.178.22        192.168.178.20        TCP      66     34671→445 [ACK] Seq=530 Ack=486 Win=16768 Len=0 TSval=705037 TSecr=4539598

Frame 14: 66 bytes on wire (528 bits), 66 bytes captured (528 bits) on interface 0
Ethernet II, Src: HonHaiPr_a1:9e:e3 (14:2d:27:a1:9e:e3), Dst: IntelCor_f7:53:65 (00:1c:c0:f7:53:65)
Internet Protocol Version 4, Src: 192.168.178.22 (192.168.178.22), Dst: 192.168.178.20 (192.168.178.20)
Transmission Control Protocol, Src Port: 34671 (34671), Dst Port: 445 (445), Seq: 530, Ack: 486, Len: 0

No.     Time           Source                Destination           Protocol Length Info
     15 89.269838000   192.168.178.22        192.168.178.20        TCP      66     [TCP Keep-Alive] 34671→445 [ACK] Seq=529 Ack=486 Win=16768 Len=0 TSval=750080 TSecr=4539598

Frame 15: 66 bytes on wire (528 bits), 66 bytes captured (528 bits) on interface 0
Ethernet II, Src: HonHaiPr_a1:9e:e3 (14:2d:27:a1:9e:e3), Dst: IntelCor_f7:53:65 (00:1c:c0:f7:53:65)
Internet Protocol Version 4, Src: 192.168.178.22 (192.168.178.22), Dst: 192.168.178.20 (192.168.178.20)
Transmission Control Protocol, Src Port: 34671 (34671), Dst Port: 445 (445), Seq: 529, Ack: 486, Len: 0

No.     Time           Source                Destination           Protocol Length Info
     16 89.269898000   192.168.178.20        192.168.178.22        TCP      66     [TCP Keep-Alive ACK] 445→34671 [ACK] Seq=486 Ack=530 Win=66048 Len=0 TSval=4544102 TSecr=705037

Frame 16: 66 bytes on wire (528 bits), 66 bytes captured (528 bits) on interface 0
Ethernet II, Src: IntelCor_f7:53:65 (00:1c:c0:f7:53:65), Dst: HonHaiPr_a1:9e:e3 (14:2d:27:a1:9e:e3)
Internet Protocol Version 4, Src: 192.168.178.20 (192.168.178.20), Dst: 192.168.178.22 (192.168.178.22)
Transmission Control Protocol, Src Port: 445 (445), Dst Port: 34671 (34671), Seq: 486, Ack: 530, Len: 0

**Comment by yoichiro** [comment] 2015-09-04 14:59
@cottonwool You can change the debug log level by clicking the gear icon. I would like you to collect the detail error log and put them here.

**Comment by cottonwool** [comment] 2015-09-04 15:37
I can't find where to set the debug log level.
I've looked under the gear icon of the app.
I've looked under the gear icon of the debug console.
I am not running chromeos in developer mode, does that make a difference?
I've googled for how to do this but nothing useful came up.
Help?

**Comment by yoichiro** [comment] 2015-09-06 14:04
@cottonwool I have just released a new version 2.0.3 including the settings I mentioned at the previous comment. You should be able to find the gear icon. Could you confirm the debug log once again?

**Comment by cottonwool** [comment] 2015-09-06 19:54
I've got the new version with the settings options but it will be a day or so before I can try them out.

**Comment by pmontelo** [comment] 2015-09-07 15:50
@yoichiro I'm getting the same error (c000000d) using v2.0.3 connecting to a share on a Windows 7 desktop that is part of my active directory domain.  If I change the max protocol version to SMB1, then I can connect but SMB2 always fails with NT_STATUS_INVALID_PARAMETER.

If you can tell me how to collect the log output, I can send them to you.

**Comment by yoichiro** [comment] 2015-09-08 00:21
I could reproduce this issue with my Win7. Well, I intend to fix this issue as a high priority.

**Comment by yoichiro** [comment] 2015-09-18 13:18
@cottonwool @pmontelo I just released a new version 2.1.1. This version includes a new logic to support connecting to Win7. It would be great if you could do a connection test with the latest version.

**Comment by cottonwool** [comment] 2015-09-18 14:53
@yoichiro I've started by using max protocol version = SMB1/CIFS with Log Level = Trace but no console window open. I tried my usual usage of playing audio files with Audio Player and browsing around the folders of my share at the same time.

This works OK. I've been playing audio for >20 minutes without a hangup. This was a >14 minute track followed by a >6 minute track. Before this version the audio would have stopped playing after around 5 minutes with no console / background window open. Browsing the folders worked OK to with a small delay at one point.

I'll try next with SMB2.

**Comment by cottonwool** [comment] 2015-09-18 15:06
@yoichiro Trying now with SMB2 and Log Level = Trace and no background / console window. The result was that it seemed to be successful then I got a pop-up warning about a task taking longer than expected and the shared folder did NOT appear in the Files window.

I tried again with the same share but with Info log level / no background window and got a message to say it was already mounted.

I tried again with another share and Info log level / no background window and it appeared to succeed but the shared folder did NOT appear in the Files window.

I'm accessing the app both by using the app icon which I have stuck to my shelf, and through the Add New Services option of the Files app.

I've tried mounting both shares again through the app and I'm being told they are already mounted but getting pop-up "An operation is taking longer than expected. Do you want to abort it"

**Comment by cottonwool** [comment] 2015-09-18 15:17
@yoichiro I've rebooted my chromebook and went to try again with SMB2 and the same shares. I did not check the files app but went straight to the SMB app to mount one of the shares. When I clicked MOUNT I got an "Already mounted" message.

I went to the files app and both shares were visible to use. (This is the issue with there being no control over shares reconnecting automatically at startup)

I'm now playing audio across one of the shares and I will let you know how it goes.

I'll have to stop testing after that but I will hopefully try more things later: e.g. does switching between SMB1 and SMB2 cause the problem seen.

**Comment by cottonwool** [comment] 2015-09-18 15:59
In my opinion the original issue (c000000d: NT_STATUS_INVALID_PARAMETER) is fixed.

I closed the shares. Rebooted. Checked the settings were SMB2 and Log Level = Info and no background / console window. I mounted a share and played and audio file. I have got two pop-ups "An operation is taking longer than expected. Do you want to abort it" One from the Audio Player app and one from the general notification area. Then after 3'16" the audio stopped playing. Restarting the audio by selecting another track and I get the same "An operation is taking longer ..." pop-up appearing repeatedly. This should be a new issue.

**Comment by pmontelo** [comment] 2015-09-18 19:53
@yoichiro the SMB2 connection problem seems to be fixed.  It's working fine for me with your new version. Thanks.

**Comment by yoichiro** [comment] 2015-10-12 11:18
OK, I close this issue. Thank you for the reporting.

**Closed as completed by yoichiro** 2015-10-12 11:18 UTC
