### ISSUE TITLE
Does not connect - just sits there

### ISSUE THREAD

**Issue by simmondp** [yoichiro/chromeos-filesystem-cifs#66] opened 2015-06-23 15:42 UTC
This is trying to connect to a fileserver share on a Windows 7 desktop
IPAddress: 192.1682.34
Port 445
Username: Paul
Password: <correct username>
Domain name: DROVECREST (as set on the WORKGROUP on the PC)

Chromebook is an Acer C720

background.js:6160 Object
background.js:6160 Client#login
background.js:6160 connect
background.js:6167 Packet
background.js:6160 writePacket
background.js:6160 readPacket
background.js:6160 _readPacketSize
background.js:6160 _readPacketSize - 2
background.js:6160 readPacket: 127
background.js:6174 CAP_EXTENDED_SECURITY: true
background.js:6174 CAP_COMPRESSED_DATA: false
background.js:6174 CAP_BULK_TRANSFER: false
background.js:6174 CAP_UNIX: false
background.js:6174 CAP_LARGE_WRITEX: true
background.js:6174 CAP_LARGE_READX: true
background.js:6174 CAP_INFOLEVEL_PASSTHROUGH: true
background.js:6174 CAP_DFS: false
background.js:6174 CAP_NT_FIND: true
background.js:6174 CAP_LOCK_AND_READ: true
background.js:6174 CAP_LEVEL_II_OPLOCKS: true
background.js:6174 CAP_STATUS32: true
background.js:6174 CAP_RPC_REMOTE_APIS: true
background.js:6174 CAP_NT_SMBS: true
background.js:6174 CAP_LARGE_FILES: true
background.js:6174 CAP_UNICODE: true
background.js:6174 CAP_MPX_MODE: false
background.js:6174 CAP_RAW_MODE: false
background.js:6174 NEGOTIATE_SECURITY_SIGNATURES_REQUIRED: 0
background.js:6174 NEGOTIATE_SECURITY_SIGNATURES_ENABLED: 0
background.js:6174 NEGOTIATE_SECURITY_CHALLENGE_RESPONSE: 1
background.js:6174 NEGOTIATE_SECURITY_USER_LEVEL: 1
background.js:6167 Header
background.js:6167 NegotiateProtocolResponse
background.js:6167 Packet
background.js:6160 writePacket
background.js:6160 readPacket
background.js:6160 _readPacketSize
background.js:6160 _readPacketSize - 2
background.js:6160 readPacket: 411
background.js:6167 Header
background.js:6174 NTLMSSP_NEGOTIATE_UNICODE: true
background.js:6174 NTLMSSP_NEGOTIATE_OEM: false
background.js:6174 NTLMSSP_REQUEST_TARGET: true
background.js:6174 NTLMSSP_NEGOTIATE_SIGN: false
background.js:6174 NTLMSSP_NEGOTIATE_SEAL: false
background.js:6174 NTLMSSP_NEGOTIATE_DATAGRAM_STYLE: false
background.js:6174 NTLMSSP_NEGOTIATE_LM_KEY: false
background.js:6174 NTLMSSP_NEGOTIATE_NETWARE: false
background.js:6174 NTLMSSP_NEGOTIATE_NTLM: true
background.js:6174 NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED: false
background.js:6174 NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED: false
background.js:6174 NTLMSSP_NEGOTIATE_LOCAL_CALL: false
background.js:6174 NTLMSSP_NEGOTIATE_ALWAYS_SIGN: false
background.js:6174 NTLMSSP_TARGET_TYPE_DOMAIN: false
background.js:6174 NTLMSSP_TARGET_TYPE_SERVER: true
background.js:6174 NTLMSSP_TARGET_TYPE_SHARE: false
background.js:6174 NTLMSSP_NEGOTIATE_NTLM2: true
background.js:6174 NTLMSSP_REQUEST_INIT_RESPONSE: false
background.js:6174 NTLMSSP_REQUEST_ACCEPT_RESPONSE: false
background.js:6174 NTLMSSP_REQUEST_NON_NT_SESSION_KEY: false
background.js:6174 NTLMSSP_NEGOTIATE_TARGET_INFO: true
background.js:6174 NTLMSSP_NEGOTIATE_128: true
background.js:6174 NTLMSSP_NEGOTIATE_KEY_EXCH: false
background.js:6174 NTLMSSP_NEGOTIATE_56: false
background.js:6167 Packet
background.js:6160 writePacket
background.js:6160 readPacket
background.js:6160 _readPacketSize
background.js:6160 _readPacketSize - 2
background.js:6160 readPacket: 183
background.js:6160 Client#getSharedResourceList
background.js:6167 Packet
background.js:6160 writePacket
background.js:6160 readPacket
background.js:6160 _readPacketSize
background.js:6160 _readPacketSize - 2
background.js:6160 readPacket: 48
background.js:6167 Header
background.js:6167 TreeConnectAndxResponse
background.js:6167 Packet
background.js:6160 writePacket
background.js:6160 readPacket
background.js:6160 _readPacketSize
background.js:6160 _readPacketSize - 2
background.js:6160 readPacket: 135
background.js:6167 Header
background.js:6167 NtCreateAndxResponse
background.js:6167 Packet
background.js:6160 writePacket
background.js:6160 readPacket
background.js:6160 _readPacketSize
background.js:6160 _readPacketSize - 2
background.js:6160 readPacket: 1148
background.js:6167 Header
background.js:6167 DceRpcBindAck
background.js:6167 Packet
background.js:6160 writePacket
background.js:6160 readPacket
background.js:6160 _readPacketSize
background.js:6160 _readPacketSize - 2
background.js:6160 readPacket: 2104
background.js:6167 FF 53 4D 42 25 05 00 00 80 98 03 C8 00 00 00 00 
00 00 00 00 00 00 00 00 00 08 18 00 00 08 07 00 
0A 00 00 00 04 00 00 00 00 38 00 00 00 00 04 38 
04 00 00 00 00 01 08 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 05 00 02 03 10 00 00 00 
38 06 00 00 02 00 00 00 20 06 00 00 00 00 00 00 
01 00 00 00 01 00 00 00 00 00 02 00 18 00 00 00 
04 00 02 00 18 00 00 00 08 00 02 00 00 00 00 80 
0C 00 02 00 10 00 02 00 00 00 00 00 14 00 02 00 
18 00 02 00 00 00 00 80 1C 00 02 00 20 00 02 00 
00 00 00 80 24 00 02 00 28 00 02 00 00 00 00 80 
2C 00 02 00 30 00 02 00 00 00 00 00 34 00 02 00 
38 00 02 00 03 00 00 80 3C 00 02 00 40 00 02 00 
00 00 00 00 44 00 02 00 48 00 02 00 00 00 00 00 
4C 00 02 00 50 00 02 00 00 00 00 00 54 00 02 00 
58 00 02 00 00 00 00 00 5C 00 02 00 60 00 02 00 
00 00 00 00 64 00 02 00 68 00 02 00 00 00 00 00 
6C 00 02 00 70 00 02 00 00 00 00 00 74 00 02 00 
78 00 02 00 00 00 00 80 7C 00 02 00 80 00 02 00 
00 00 00 80 84 00 02 00 88 00 02 00 00 00 00 00 
8C 00 02 00 90 00 02 00 00 00 00 80 94 00 02 00 
98 00 02 00 00 00 00 00 9C 00 02 00 A0 00 02 00 
00 00 00 80 A4 00 02 00 A8 00 02 00 00 00 00 00 
AC 00 02 00 B0 00 02 00 00 00 00 00 B4 00 02 00 
B8 00 02 00 00 00 00 80 BC 00 02 00 C0 00 02 00 
00 00 00 80 C4 00 02 00 07 00 00 00 00 00 00 00 
07 00 00 00 41 00 44 00 4D 00 49 00 4E 00 24 00 
00 00 00 00 0D 00 00 00 00 00 00 00 0D 00 00 00 
52 00 65 00 6D 00 6F 00 74 00 65 00 20 00 41 00 
64 00 6D 00 69 00 6E 00 00 00 00 00 06 00 00 00 
00 00 00 00 06 00 00 00 41 00 6C 00 69 00 63 00 
65 00 00 00 01 00 00 00 00 00 00 00 01 00 00 00 
00 00 00 00 03 00 00 00 00 00 00 00 03 00 00 00 
43 00 24 00 00 00 00 00 0E 00 00 00 00 00 00 00 
0E 00 00 00 44 00 65 00 66 00 61 00 75 00 6C 00 
74 00 20 00 73 00 68 00 61 00 72 00 65 00 00 00 
03 00 00 00 00 00 00 00 03 00 00 00 44 00 24 00 
00 00 00 00 0E 00 00 00 00 00 00 00 0E 00 00 00 
44 00 65 00 66 00 61 00 75 00 6C 00 74 00 20 00 
73 00 68 00 61 00 72 00 65 00 00 00 03 00 00 00 
00 00 00 00 03 00 00 00 45 00 24 00 00 00 00 00 
0E 00 00 00 00 00 00 00 0E 00 00 00 44 00 65 00 
66 00 61 00 75 00 6C 00 74 00 20 00 73 00 68 00 
61 00 72 00 65 00 00 00 05 00 00 00 00 00 00 00 
05 00 00 00 45 00 6D 00 6D 00 61 00 00 00 00 00 
01 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 
05 00 00 00 00 00 00 00 05 00 00 00 49 00 50 00 
43 00 24 00 00 00 00 00 0B 00 00 00 00 00 00 00 
0B 00 00 00 52 00 65 00 6D 00 6F 00 74 00 65 00 
20 00 49 00 50 00 43 00 00 00 00 00 04 00 00 00 
00 00 00 00 04 00 00 00 4C 00 69 00 7A 00 00 00 
01 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 
08 00 00 00 00 00 00 00 08 00 00 00 4D 00 61 00 
74 00 74 00 68 00 65 00 77 00 00 00 01 00 00 00 
00 00 00 00 01 00 00 00 00 00 00 00 05 00 00 00 
00 00 00 00 05 00 00 00 4D 00 69 00 64 00 69 00 
00 00 00 00 01 00 00 00 00 00 00 00 01 00 00 00 
00 00 00 00 06 00 00 00 00 00 00 00 06 00 00 00 
4D 00 75 00 73 00 69 00 63 00 00 00 01 00 00 00 
00 00 00 00 01 00 00 00 00 00 00 00 05 00 00 00 
00 00 00 00 05 00 00 00 50 00 61 00 75 00 6C 00 
00 00 00 00 01 00 00 00 00 00 00 00 01 00 00 00 
00 00 00 00 07 00 00 00 00 00 00 00 07 00 00 00 
50 00 68 00 6F 00 74 00 6F 00 73 00 00 00 00 00 
01 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 
07 00 00 00 00 00 00 00 07 00 00 00 70 00 72 00 
69 00 6E 00 74 00 24 00 00 00 00 00 10 00 00 00 
00 00 00 00 10 00 00 00 50 00 72 00 69 00 6E 00 
74 00 65 00 72 00 20 00 
background.js:6167 Headercommand_: 37errorClass_: 5errorCode_: 32768flag2_: 51203flag_: 152multiplexId_: 7ntStyleErrorCode_: 2147483653processId_: 24protocol_: "SMB"treeId_: 2048types_: TypesuserId_: 2048__proto__: Header
background.js:6174 0x80000005: STATUS_BUFFER_OVERFLOW: Normal for DCERPC named pipes. Ignore.
extensions::uncaught_exception_handler:8 Error in event handler for sockets.tcp.onReceive: RangeError: Offset is outside the bounds of the DataView
    at Types.getFixed4BytesValue (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:6583:27)
    at readString (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:9382:36)
    at DceRpcNetShareEnumAllResponse.load (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:9356:41)
    at Protocol.parseDceRpcNetShareEnumAllResponsePacket (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:11080:39)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:12559:44)
    at null.<anonymous> (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:11482:21)
    at ChromeSocket2.fetch (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:11710:26)
    at ChromeSocket2.fetch (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:11712:26)
    at _appendReceivedData (chrome-extension://mfhnnfciefdpolbelmfkpmhhmlkehbdf/background.js:11595:14)handler @ extensions::uncaught_exception_handler:8

**Comment by yoichiro** [comment] 2015-06-25 22:06
@simmondp Finally, I could reproduce this issue on my environment. I will be able to fix this issue.

**Comment by yoichiro** [comment] 2015-06-25 22:11
@simmondp This issue is duplicate of #16. I close this issue. Please refer the status of #16. Thank you for this reporting.

**Closed as completed by yoichiro** 2015-06-25 22:11 UTC

**Comment by simmondp** [comment] 2015-06-26 08:06
Tried the updated version - fixed successfully.
Keep up the good work!
Many thanks
